import { copilotNeverList, neverListExclusion, type CopilotNeverListEntry } from "./neverList.js";

interface CatalogCoverageExclusion {
  readonly disposition: "deferred" | "permanent";
  readonly reason: string;
  readonly neverListEntry?: CopilotNeverListEntry;
}

type CatalogCoverageEntry = string | CatalogCoverageExclusion;

const deferred = (reason: string): CatalogCoverageExclusion => ({ disposition: "deferred", reason });
const permanent = (reason: string): CatalogCoverageExclusion => ({ disposition: "permanent", reason });
const coverage = (operationIds: ReadonlyArray<string>, entry: CatalogCoverageExclusion): Record<string, CatalogCoverageExclusion> =>
  Object.fromEntries(operationIds.map((operationId) => [operationId, entry]));

const catalogToolCoverage = {
  listAgents: "agent_configuration",
  getAgent: "agent_configuration",
  listAgentDirectives: "agent_configuration",
  listAgentRoutines: "routine_definition",
  getAgentRoutine: "routine_definition",
  getAgentRoutinePortableDocument: "routine_definition",
  getHistoryConversation: "conversation_transcript",
  tailHistoryConversation: "conversation_transcript",
  getLegacyHistoryConversation: "conversation_transcript",
  listHistory: "conversation_history_search",
  listChatHistory: "conversation_history_search",
  listHistorySearches: "conversation_history_search",
  getHistorySearch: "conversation_history_search",
  searchDocuments: "document_search",
  getDocument: "document_search",
  listDocuments: "document_status",
  listDocumentSources: "document_status",
  listDocumentsBySource: "document_status",
  listAgentSkills: "agent_skills",
  listAgentSkillCapabilities: "agent_skills",
  listMcpConnections: "agent_skills",
  getMcpConnection: "agent_skills",
  listExternalSkills: "agent_skills",
  getExternalSkill: "agent_skills",
  getEvalCaseBySourceMessage: "eval_results",
  getOrCreateEvalCaseBySourceMessage: "eval_results",
  listLowQualityTurns: "quality_signals",
  getQualityStats: "quality_signals",
  getAudiencePulse: "audience_topics",
} as const;

const wave2BehaviorAuthoring = deferred("Deferred to Wave 2 behavior authoring: Ray will create operator-confirmed proposals, not edit live behavior directly.");
const wave3KnowledgeBase = deferred("Deferred to Wave 3 knowledge base work: document and source changes need their own bounded proposal flows.");
// Ingestion settings become proposable in Wave 3. Only the embedding-model switch inside such a
// proposal stays never-list, because it triggers a bulk re-embed; cancelling a pending switch is a
// safe de-escalation and is deliberately not treated as a boundary.
const wave3IngestionSettings = deferred(
  `Deferred to Wave 3 ingestion settings proposals. ${copilotNeverList.embedding_model_switch_without_typed_confirmation.reason}`,
);
const wave4Serving = deferred("Deferred to Wave 4 serving work: operator serving controls need an explicit runtime safety model.");
const wave5WorkspaceConfig = deferred("Deferred to Wave 5 workspace configuration: these settings need bounded, operator-confirmed configuration flows.");
const identityOrSecrets = permanent("Permanent exclusion: identity, authorization, and secret-bearing administration are not an operator-copilot surface.");
const endUserSurface = permanent("Permanent exclusion: this is an end-user or inbound integration surface, not an operator-copilot tool.");
const authOrRegistration = permanent("Permanent exclusion: authentication and registration are not an operator-copilot surface.");
const copilotUiOnly = permanent("Permanent exclusion: this endpoint is the operator copilot UI/control surface, not a tool Ray may call.");

/** Every OpenAPI operation is deliberately reachable through a family reader or explicitly planned/excluded. */
export const catalogCoverage: Record<string, CatalogCoverageEntry> = {
  ...catalogToolCoverage,

  ...coverage([
    "getHealth",
    "createPublicChatSession",
    "getRegistrationAvailability",
    "registerAccount",
    "loginAccount",
    "requestPasswordReset",
    "confirmPasswordReset",
    "verifyEmail",
    "resendEmailVerification",
    "getAccountInvitation",
    "acceptAccountInvitation",
  ], authOrRegistration),
  ...coverage([
    "createAdditionalOrganization",
    "listAccessibleAccounts",
    "listAccountUsers",
    "switchAccount",
    "getWorkspaceApiToken",
    "getWorkspaceMcpContext",
    "listWorkspaceProviderCredentials",
    "getAgentContextVariableSigningKey",
    "listAgentMcpConverseGrants",
  ], identityOrSecrets),
  ...coverage(["deleteWorkspace"], neverListExclusion("workspace_delete")),
  ...coverage([
    "createAccountInvitation",
    "revokeAccountInvitation",
    "updateAccountUserRole",
    "removeAccountUser",
  ], neverListExclusion("member_management")),
  ...coverage([
    "setWorkspaceGrant",
    "removeWorkspaceGrant",
    "issueAgentMcpConverseGrant",
    "revokeAgentMcpConverseGrant",
  ], neverListExclusion("access_grants")),
  ...coverage([
    "rotateWorkspaceApiToken",
    "rotateWebhookDestinationSecret",
    "rotateAnonymousChatToken",
    "rotateWebsiteEmbedToken",
    "rotateAgentMcpConverseGrant",
  ], neverListExclusion("secret_rotation")),
  ...coverage([
    "setWorkspaceProviderCredential",
    "removeWorkspaceProviderCredential",
  ], neverListExclusion("provider_credential_writes")),
  ...coverage([
    "updateIngestionSettings",
    "cancelPendingEmbeddingModel",
  ], wave3IngestionSettings),
  ...coverage(["replyToConversation"], neverListExclusion("unattended_live_customer_reply")),

  ...coverage([
    "getAccountUsageTrends",
    "getAccountUsageMessages",
    "getAccountInternalUsage",
    "listWorkspaces",
    "createWorkspace",
    "getWorkspaceSummary",
    "resolveWorkspaceRouteKey",
    "renameWorkspace",
    "listWebhookDestinations",
    "createWebhookDestination",
    "getWebhookDestination",
    "updateWebhookDestination",
    "deleteWebhookDestination",
    "getPlatformSettings",
    "updatePlatformSettings",
    "getSettingsRetrievalDefaults",
    "getIngestionSettings",
    "reprocessWorkspaceIngestion",
    "getGeneralSettings",
    "updateGeneralSettings",
    "uploadAssistantLogo",
    "deleteAssistantLogo",
    "getWorkspaceLlmModels",
    "updateWorkspaceLlmModels",
    "startMcpConnectionOauth",
    "createWorkspaceOauthConnection",
    "listWorkspaceOauthConnections",
    "getWorkspaceOauthConnection",
    "reauthorizeWorkspaceOauthConnection",
    "listWorkspaceEmailSkillActivity",
    "listWorkspaceEmailConnections",
    "createWorkspaceEmailConnection",
    "listWorkspaceEmailOauthConnections",
    "updateWorkspaceEmailConnection",
    "deleteWorkspaceEmailConnection",
    "checkWorkspaceEmailConnectionHealth",
    "startWorkspaceSlackInstall",
    "getWorkspaceSlackInstallStatus",
    "getWorkspaceSlackManifest",
    "getWorkspaceSlackBinding",
    "setWorkspaceSlackBinding",
    "deleteWorkspaceSlackChannelBinding",
    "listWorkspaceSlackBindings",
    "disconnectWorkspaceSlackInstallation",
    "listConnectors",
    "getConnectorDetail",
    "updateConnectorConfig",
    "enableConnector",
    "disableConnector",
    "syncConnector",
  ], wave5WorkspaceConfig),
  ...coverage([
    "createAgent",
    "updateAgent",
    "getAgentChannelsLifecycle",
    "createAgentDirective",
    "draftAgentDirective",
    "updateAgentDirective",
    "deleteAgentDirective",
    "listAgentRoutineSkillCatalog",
    "createAgentRoutine",
    "updateAgentRoutine",
    "deleteAgentRoutine",
    "updateAgentRoutinePortableDocument",
    "draftAgentRoutineFromProcedure",
    "createAgentRoutinePortableDocument",
    "canonicalizeRoutinePortableDocument",
    "validateAgentRoutine",
    "publishAgentRoutine",
    "reviseAgentRoutine",
    "archiveAgentRoutine",
    "restoreAgentRoutine",
    "uploadAgentAssistantLogo",
    "deleteAgentAssistantLogo",
    "setDefaultAgent",
    "createContextVariable",
    "listContextVariables",
    "getContextVariable",
    "updateContextVariable",
    "deleteContextVariable",
    "listAgentContextVariables",
    "upsertAgentContextVariable",
    "deleteAgentContextVariable",
    "upsertContextVariableValue",
    "getContextVariableValue",
    "deleteContextVariableValue",
    "listSkills",
    "getSkill",
    "createMcpConnection",
    "discoverMcpConnectionTools",
    "deleteMcpConnection",
    "updateMcpConnection",
    "createExternalSkill",
    "deleteExternalSkill",
    "updateExternalSkill",
    "listAgentEmailSkills",
    "createAgentEmailSkill",
    "getAgentEmailSkill",
    "updateAgentEmailSkill",
    "deleteAgentEmailSkill",
    "listAgentWebhookSkills",
    "createAgentWebhookSkill",
    "getAgentWebhookSkill",
    "updateAgentWebhookSkill",
    "deleteAgentWebhookSkill",
    "listAgentSlackSkills",
    "createAgentSlackSkill",
    "getAgentSlackSkill",
    "updateAgentSlackSkill",
    "deleteAgentSlackSkill",
    "createAgentSkill",
    "updateAgentSkill",
    "deleteAgentSkill",
    "deleteEvalCase",
    "createEvalRun",
  ], wave2BehaviorAuthoring),
  ...coverage([
    "searchRetrievalEvidence",
    "listDocumentSearchHistory",
    "getDocumentSearchHistory",
    "createDocument",
    "updateDocumentSource",
    "deleteDocumentSource",
    "recrawlDocumentSource",
    "pauseDocumentSourceCrawl",
    "resumeDocumentSourceCrawl",
    "importDocument",
    "crawlWebsiteDocuments",
    "listWebsiteCrawlJobs",
    "deleteWebsiteCrawlJob",
    "updateDocument",
    "updateDocumentRetrieval",
    "deleteDocument",
    "reprocessDocumentSource",
    "reprocessDocument",
  ], wave3KnowledgeBase),
  ...coverage([
    "createRetrievalAnswer",
    "setQualityTurnTriage",
    "refreshAudiencePulse",
    "getAudiencePulseEvidenceAnchor",
  ], wave4Serving),
  ...coverage([
    "completeMcpConnectionOauth",
    "completeWorkspaceOauthCallback",
    "createAssistantChatResponse",
    "upsertAnswerFeedback",
    "clearAnswerFeedback",
    "upsertPublicAnswerFeedback",
    "clearPublicAnswerFeedback",
    "takeOverConversation",
    "transferConversationOwnership",
    "handBackConversation",
    "forkConversation",
    "listPendingDecisions",
    "resolveDecision",
    "createMcpConverseSession",
    "validateMcpConverseSession",
    "askMcpConverseAgent",
    "answerMcpConverseGrounded",
    "listMcpConverseResources",
    "readMcpConverseResource",
    "createPublicChatResponse",
    "listPublicChatHistory",
    "getPublicChatHistoryConversation",
    "tailPublicChatHistoryConversation",
    "streamPublicChatConversationEvents",
  ], endUserSurface),

  createAgentDirective: "propose_directive",
  updateAgentDirective: "propose_directive",
  updateAgent: "propose_agent_setting",
  createAgentRoutine: "propose_routine",
  updateAgentRoutine: deferred("Deferred to Wave 2 behavior authoring: routine proposals create drafts only; editing remains in the routine editor."),
  updateAgentRoutinePortableDocument: deferred("Deferred to Wave 2 behavior authoring: routine proposals create drafts only; portable editing remains in the routine editor."),
  draftAgentRoutineFromProcedure: deferred("Deferred to Wave 2 behavior authoring: routine proposals create drafts only; drafting remains in the routine editor."),
  createAgentRoutinePortableDocument: deferred("Deferred to Wave 2 behavior authoring: routine proposals create drafts only; portable authoring remains in the routine editor."),
  canonicalizeRoutinePortableDocument: deferred("Deferred to Wave 2 behavior authoring: portable routine editing remains in the routine editor."),
  validateAgentRoutine: deferred("Deferred to Wave 2 behavior authoring: routine validation remains in the routine editor."),
  publishAgentRoutine: deferred("Deferred to Wave 2 behavior authoring: publishing remains in the routine editor."),
  reviseAgentRoutine: deferred("Deferred to Wave 2 behavior authoring: revision remains in the routine editor."),
  archiveAgentRoutine: deferred("Deferred to Wave 2 behavior authoring: lifecycle changes remain in the routine editor."),
  restoreAgentRoutine: deferred("Deferred to Wave 2 behavior authoring: lifecycle changes remain in the routine editor."),
  getCopilotAvailability: copilotUiOnly,
  listCopilotConversations: copilotUiOnly,
  getCopilotConversation: copilotUiOnly,
  deleteCopilotConversation: copilotUiOnly,
  createCopilotTurn: copilotUiOnly,
  getCopilotProposal: copilotUiOnly,
  applyCopilotProposal: copilotUiOnly,
  dismissCopilotProposal: copilotUiOnly,
};
