import { readFile } from "node:fs/promises";

import { describe, expect, it } from "vitest";

import { catalogCoverage } from "../../../src/modules/operatorCopilot/catalogCoverage.js";
import { copilotProposalOperationIds } from "../../../src/app/http/openapi/paths/copilotPaths.js";

describe("operator copilot catalog coverage", () => {
  it("maps every OpenAPI operation to a catalog tool or stated exclusion", async () => {
    const openApi = JSON.parse(await readFile(new URL("../../../openapi.json", import.meta.url), "utf8")) as {
      paths: Record<string, Record<string, { operationId?: string }>>;
    };
    const operationIds = Object.values(openApi.paths)
      .flatMap((path) => Object.values(path))
      .flatMap((operation) => operation.operationId ? [operation.operationId] : []);

    // OpenAPI artifacts are generated by the orchestrator. Include newly
    // registered source operation IDs so this remains a useful local gate before
    // that generation step and exact again once artifacts are refreshed.
    expect(Object.keys(catalogCoverage).sort()).toEqual([...new Set([...operationIds, ...copilotProposalOperationIds])].sort());
    for (const entry of Object.values(catalogCoverage)) {
      expect(typeof entry === "string" || ("excluded" in entry && entry.excluded.trim().length > 0)).toBe(true);
    }
  });
});
