import { readFile } from "node:fs/promises";

import { describe, expect, it } from "vitest";

import { catalogCoverage } from "../../../src/modules/operatorCopilot/catalogCoverage.js";
import { copilotProposalOperationIds } from "../../../src/app/http/openapi/paths/copilotPaths.js";

describe("operator copilot catalog coverage", () => {
  // Ratchet: this may only ever decrease as tools land. It went 131 -> 133 once, when ingestion
  // settings were reclassified from a permanent exclusion to Wave 3 planned work — an honest
  // increase in the backlog, not deferred scope creep.
  const maxDeferredCatalogExclusions = 128;

  it("maps agent and routine discovery operations to the completed family readers", () => {
    expect(catalogCoverage).toMatchObject({
      listAgents: "agent_configuration",
      listAgentDirectives: "agent_configuration",
      listAgentRoutines: "routine_definition",
    });
  });

  it("maps conversation history operations to the bounded transcript reader", () => {
    expect(catalogCoverage).toMatchObject({
      getHistoryConversation: "conversation_transcript",
      tailHistoryConversation: "conversation_transcript",
      getLegacyHistoryConversation: "conversation_transcript",
    });
  });

  it("maps safe workspace settings reads to the workspace settings reader", () => {
    expect(catalogCoverage).toMatchObject({
      getPlatformSettings: "workspace_settings",
      getSettingsRetrievalDefaults: "workspace_settings",
      getIngestionSettings: "workspace_settings",
      getGeneralSettings: "workspace_settings",
      listWorkspaceProviderCredentials: "workspace_settings",
      getWorkspaceLlmModels: "workspace_settings",
    });
  });

  it("maps every OpenAPI operation to a catalog tool or stated exclusion", async () => {
    const openApi = JSON.parse(await readFile(new URL("../../../openapi.json", import.meta.url), "utf8")) as {
      paths: Record<string, Record<string, { operationId?: string }>>;
    };
    const operationIds = Object.values(openApi.paths)
      .flatMap((path) => Object.values(path))
      .flatMap((operation) => operation.operationId ? [operation.operationId] : []);

    // OpenAPI artifacts are generated by the orchestrator. Include newly
    // registered source operation IDs so this remains a useful local gate before
    // that generation step and exact again once artifacts are refreshed.
    expect(Object.keys(catalogCoverage).sort()).toEqual([...new Set([...operationIds, ...copilotProposalOperationIds])].sort());
    for (const entry of Object.values(catalogCoverage)) {
      expect(typeof entry === "string" || ("reason" in entry && entry.reason.trim().length > 0)).toBe(true);
    }
  });

  it("does not expand the deferred catalog backlog", () => {
    const deferredExclusionCount = Object.values(catalogCoverage)
      .filter((entry): entry is Exclude<typeof entry, string> => typeof entry !== "string")
      .filter((entry) => entry.disposition === "deferred")
      .length;

    expect(deferredExclusionCount).toBeLessThanOrEqual(maxDeferredCatalogExclusions);
  });

  it("cites the never-list for permanent copilot boundaries", () => {
    expect(catalogCoverage).toMatchObject({
      deleteWorkspace: { disposition: "permanent", neverListEntry: "workspace_delete" },
      createAccountInvitation: { disposition: "permanent", neverListEntry: "member_management" },
      setWorkspaceGrant: { disposition: "permanent", neverListEntry: "access_grants" },
      rotateWorkspaceApiToken: { disposition: "permanent", neverListEntry: "secret_rotation" },
      setWorkspaceProviderCredential: { disposition: "permanent", neverListEntry: "provider_credential_writes" },
      replyToConversation: { disposition: "permanent", neverListEntry: "unattended_live_customer_reply" },
    });
  });

  it("defers ingestion settings rather than excluding them, while keeping the embedding-model guard visible", () => {
    // The never-list entry covers the embedding-model switch inside a future proposal, not the whole
    // endpoint: Wave 3 makes ingestion settings proposable, and cancelling a pending model change is
    // a safe de-escalation rather than a boundary.
    for (const operationId of ["updateIngestionSettings", "cancelPendingEmbeddingModel"]) {
      const entry = catalogCoverage[operationId];
      expect(entry).toMatchObject({ disposition: "deferred" });
      expect(typeof entry === "string" ? "" : entry.reason).toContain("Embedding-model changes require");
    }
  });
});
