import { z } from "zod";
import type { OpenAPIRegistry } from "@asteasolutions/zod-to-openapi";
import type { OpenApiSecurity } from "../openApiRegistry.js";
import { copilotPageEntityTypes, copilotProposalTargetTypes } from "../../../../modules/operatorCopilot/public.js";

const availability = z.object({ available: z.boolean(), reason: z.enum(["ok", "no_llm_capability"]), canManage: z.boolean() });
const conversation = z.object({ id: z.string().uuid(), title: z.string().nullable(), status: z.enum(["idle", "running"]), createdAt: z.string(), updatedAt: z.string() });
const pageEntityType = z.enum(copilotPageEntityTypes);
const turn = z.object({ conversationId: z.string().uuid().nullable(), message: z.string().min(1).max(8000), pageContext: z.object({ view: z.enum(["activity", "history", "agent", "documents", "workbench", "quality", "evals", "copilot", "other"]).nullable(), agentId: z.string().uuid().nullable(), conversationId: z.string().uuid().nullable(), selection: z.string().nullable().optional(), entities: z.array(z.object({ type: pageEntityType, id: z.string(), label: z.string().max(120), focused: z.boolean() })).max(30).optional() }) });
const proposalTargetType = z.enum(copilotProposalTargetTypes);
const proposalEvidenceCase = z.object({ caseId: z.string().uuid(), caseName: z.string(), runId: z.string().uuid(), before: z.enum(["pending", "passing", "failing", "error"]), after: z.enum(["pass", "fail", "error", "recorded"]), stale: z.boolean() });
const proposalEvidenceSummary = z.object({ total: z.number().int(), improved: z.number().int(), regressed: z.number().int(), unchanged: z.number().int(), stale: z.number().int() });
const proposal = z.object({ id: z.string().uuid(), targetType: proposalTargetType, targetRef: z.unknown(), target: z.object({ type: proposalTargetType, ref: z.unknown() }), targetLabel: z.string(), status: z.enum(["pending", "applied", "dismissed", "failed", "stale"]), preview: z.object({ targetLabel: z.string(), current: z.unknown().nullable(), proposed: z.unknown() }), currentVersionMatches: z.boolean(), reason: z.string().nullable().optional(), appliedRef: z.unknown().nullable(), evidence: proposalEvidenceSummary.optional(), evidenceCases: z.array(proposalEvidenceCase).nullable() });
const proposalCard = z.object({ id: z.string().uuid(), targetType: proposalTargetType, targetLabel: z.string(), summary: z.string(), status: z.enum(["pending", "applied", "dismissed", "failed", "stale"]), reason: z.string().nullable().optional(), evidence: proposalEvidenceSummary.optional() });
const conversationMessage = z.discriminatedUnion("role", [
  z.object({ id: z.string().uuid(), role: z.literal("operator"), content: z.string(), createdAt: z.string() }),
  z.object({ id: z.string().uuid(), role: z.literal("copilot"), content: z.string(), createdAt: z.string(), outcome: z.enum(["completed", "budget_exhausted", "failed"]), activity: z.array(z.object({ tool: z.string(), outcome: z.enum(["completed", "failed"]), entity: z.object({ type: z.string(), id: z.string() }).optional() })), proposals: z.array(proposalCard) }),
]);
const conversationDetail = z.object({ id: z.string().uuid(), title: z.string().nullable(), status: z.enum(["idle", "running"]), messages: z.array(conversationMessage) });
export const copilotProposalOperationIds = ["getCopilotProposal", "applyCopilotProposal", "dismissCopilotProposal"] as const;

export const registerCopilotPaths = (registry: OpenAPIRegistry, security: OpenApiSecurity): void => {
  const session = security.workspaceAdminSecurity;
  registry.registerPath({ method: "get", path: "/api/v1/copilot/availability", tags: ["Copilot"], summary: "Check operator copilot availability", description: "Dashboard session only; bearer API tokens are rejected.", operationId: "getCopilotAvailability", security: session, responses: { 200: { description: "Availability", content: { "application/json": { schema: availability } } }, 403: { description: "Forbidden" } } });
  registry.registerPath({ method: "get", path: "/api/v1/copilot/conversations", tags: ["Copilot"], summary: "List an operator's copilot conversations", operationId: "listCopilotConversations", security: session, responses: { 200: { description: "Conversations", content: { "application/json": { schema: z.object({ conversations: z.array(conversation) }) } } } } });
  registry.registerPath({ method: "get", path: "/api/v1/copilot/conversations/{conversationId}", tags: ["Copilot"], summary: "Read a copilot conversation", operationId: "getCopilotConversation", security: session, request: { params: z.object({ conversationId: z.string().uuid() }) }, responses: { 200: { description: "Conversation", content: { "application/json": { schema: conversationDetail } } }, 404: { description: "Not found" } } });
  registry.registerPath({ method: "delete", path: "/api/v1/copilot/conversations/{conversationId}", tags: ["Copilot"], summary: "Delete a copilot conversation", operationId: "deleteCopilotConversation", security: session, request: { params: z.object({ conversationId: z.string().uuid() }) }, responses: { 204: { description: "Deleted" }, 404: { description: "Not found" } } });
  registry.registerPath({ method: "post", path: "/api/v1/copilot/turns", tags: ["Copilot"], summary: "Start a streaming operator copilot turn", description: "Returns the fixed copilot SSE event stream. A turn may persist Ray-owned evaluation records and pending proposals; applying a proposal remains a separately authorized operation. Dashboard session only; bearer API tokens are rejected.", operationId: "createCopilotTurn", security: session, request: { body: { required: true, content: { "application/json": { schema: turn } } } }, responses: { 200: { description: "SSE stream", content: { "text/event-stream": { schema: z.string() } } }, 409: { description: "Conversation already running" }, 503: { description: "No LLM capability" } } });
  registry.registerPath({ method: "get", path: "/api/v1/copilot/proposals/{proposalId}", tags: ["Copilot"], summary: "Read a copilot proposal preview", operationId: "getCopilotProposal", security: session, request: { params: z.object({ proposalId: z.string().uuid() }) }, responses: { 200: { description: "Proposal", content: { "application/json": { schema: proposal } } }, 404: { description: "Not found" } } });
  registry.registerPath({ method: "post", path: "/api/v1/copilot/proposals/{proposalId}/apply", tags: ["Copilot"], summary: "Apply a pending copilot proposal", operationId: "applyCopilotProposal", security: session, request: { params: z.object({ proposalId: z.string().uuid() }) }, responses: { 200: { description: "Proposal outcome", content: { "application/json": { schema: z.object({ status: z.enum(["applied", "stale", "failed"]), appliedRef: z.unknown().optional(), reason: z.string().nullable().optional() }) } } }, 409: { description: "Proposal is not pending" }, 403: { description: "Missing agent management permission" } } });
  registry.registerPath({ method: "post", path: "/api/v1/copilot/proposals/{proposalId}/dismiss", tags: ["Copilot"], summary: "Dismiss a pending copilot proposal", operationId: "dismissCopilotProposal", security: session, request: { params: z.object({ proposalId: z.string().uuid() }) }, responses: { 200: { description: "Proposal outcome", content: { "application/json": { schema: z.object({ status: z.literal("dismissed") }) } } }, 409: { description: "Proposal is not pending" }, 404: { description: "Not found" } } });
};
