import { z } from "zod";
import type { OpenAPIRegistry } from "@asteasolutions/zod-to-openapi";
import { registerTestExecutionSchemas } from "../schemas/testExecutionSchemas.js";

/** Separate registration avoids coupling the test-execution slice to authoring schemas. */
export const registerTestExecutionPaths = (registry: OpenAPIRegistry, security: { bearerAuthScheme: { name: string } }) => {
  const schemas = registerTestExecutionSchemas(registry);
  const authenticated = [{ [security.bearerAuthScheme.name]: [] }];
  registry.registerPath({ method: "get", path: "/api/v1/agents/{agentId}/test-executions", tags: ["Agents"], summary: "List private immutable revision tests", operationId: "listAgentTestExecutions", security: authenticated, request: { params: z.object({ agentId: z.string().uuid() }), query: z.object({ limit: z.coerce.number().int().min(1).max(100).default(50), cursor: z.string().min(1).optional() }) }, responses: { 200: { description: "Private test history returned", content: { "application/json": { schema: schemas.TestExecutionHistoryListResponseSchema } } } } });
  registry.registerPath({ method: "get", path: "/api/v1/agents/{agentId}/test-executions/{executionId}", tags: ["Agents"], summary: "Get private immutable revision test evidence", operationId: "getAgentTestExecution", security: authenticated, request: { params: schemas.TestExecutionParamsSchema }, responses: { 200: { description: "Private test evidence returned", content: { "application/json": { schema: schemas.TestExecutionHistoryDetailResponseSchema } } } } });
  registry.registerPath({ method: "post", path: "/api/v1/agents/{agentId}/test-executions", tags: ["Agents"], summary: "Start an operator-private immutable revision test", operationId: "startAgentTestExecution", security: authenticated, request: { params: z.object({ agentId: z.string().uuid() }), body: { required: true, content: { "application/json": { schema: schemas.StartTestExecutionRequestSchema } } } }, responses: { 201: { description: "Private test execution created", content: { "application/json": { schema: schemas.TestExecutionSchema } } } } });
  const sse = { "text/event-stream": { schema: schemas.TestExecutionEventSchema } };
  registry.registerPath({ method: "post", path: "/api/v1/agents/{agentId}/test-executions/{executionId}/messages", tags: ["Agents"], summary: "Run a fenced private test turn", operationId: "sendAgentTestExecutionMessage", security: authenticated, request: { params: schemas.TestExecutionParamsSchema, body: { required: true, content: { "application/json": { schema: schemas.TestExecutionMessageRequestSchema } } } }, responses: { 200: { description: "Fenced side events", content: sse } } });
  registry.registerPath({ method: "post", path: "/api/v1/agents/{agentId}/test-executions/{executionId}/sides/{sideId}/retain", tags: ["Agents"], summary: "Continue one settled comparison version as a private test", operationId: "retainAgentTestExecutionSide", security: authenticated, request: { params: schemas.TestExecutionRetainParamsSchema }, responses: { 201: { description: "Single private test execution created", content: { "application/json": { schema: schemas.TestExecutionSchema } } } } });
  registry.registerPath({ method: "post", path: "/api/v1/agents/{agentId}/test-executions/{executionId}/sides/{sideId}/retry", tags: ["Agents"], summary: "Retry one failed private test side", operationId: "retryAgentTestExecutionSide", security: authenticated, request: { params: schemas.TestExecutionRetryParamsSchema, body: { required: true, content: { "application/json": { schema: schemas.TestExecutionRetryRequestSchema } } } }, responses: { 200: { description: "Fenced side events", content: sse } } });
};
