#!/usr/bin/env node
// Issue #1063: every chunk vector is stored twice — in `chunks.embedding` /
// `chunks.embedding_unbounded` and in `chunk_embeddings`. The canonical table is the one
// that carries more than one embedding width, so the legacy pair is being retired.
//
// The retirement is only mechanical while the set of files reading those columns is
// known. It was not: two readers were absent from the plan, and one of them —
// senseGroupingService — fails *silently* when the column goes, because losing vectors
// degrades clarification into never firing rather than raising. This guard turns that
// set into a checklist that cannot drift.
//
// The allowlist may only ever shrink. When it is empty the columns can be dropped, and
// this script goes with them.

import { readFileSync, readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";

export const ALLOWLIST = new Map([
  [
    "modules/retrieval/infra/vectorSearch.ts",
    "The legacy search leg itself (PgVectorIndex) plus the unwired PgVectorSearch. "
    + "Removed by #1063 step 3, once canonical coverage is verified.",
  ],
  [
    "modules/retrieval/infra/chunkVectorStorage.ts",
    "Writes both columns on every ingest. Removed by #1063 step 4.",
  ],
  [
    "modules/documents/infra/chunkRepository.ts",
    "Falls back to the legacy width when a chunk has no canonical row, so the chunk "
    + "inspector still reports a dimension mid-backfill. The fallback goes with the "
    + "columns in #1063 step 5.",
  ],
  [
    "modules/retrieval/services/senseGroupingService.ts",
    "Falls back to the legacy column for the whole batch when canonical coverage is "
    + "incomplete, rejecting the batch unless every vector has one known model. Cosine "
    + "distances cannot compare across embedding models. Removed in #1063 step 5.",
  ],
]);

// Generated from the live database schema, so it names the columns as long as they
// exist and is regenerated by `pnpm run db:types` after they are dropped. It describes
// the schema rather than reading it, so it is not part of the retirement checklist.
const GENERATED_FILES = new Set([
  "shared/infra/kysely/schema.ts",
]);

// Double-quoted SQL identifiers and double-quoted query-builder strings normalize to
// the same token shape without changing line boundaries used in diagnostics.
const normalizeIdentifiers = (source) =>
  source.replace(/"([A-Za-z_][A-Za-z0-9_]*)"/g, "$1");

const firstLegacyChunkVectorIndex = (source) => {
  const normalized = normalizeIdentifiers(source);
  const patterns = [
    /\bembedding_unbounded\b/i,
    /\b(?:c|ch|chunks)\s*\.\s*embedding\b/i,
    /\binsert\s+into\s+chunks\s*\([^)]*\bembedding\b/is,
    /\bselect\b(?:(?!\bfrom\b)[\s\S])*?\bembedding\b(?:(?!\bfrom\b)[\s\S])*?\bfrom\s+chunks\b/i,
    /\.selectFrom\(\s*["']?chunks(?:\s+as\s+[A-Za-z_][A-Za-z0-9_]*)?["']?\s*\)[\s\S]{0,2000}?\.select\(\s*\[?\s*["']?(?:[A-Za-z_][A-Za-z0-9_]*\.)?embedding["']?/i,
  ];
  const indexes = patterns
    .map((pattern) => pattern.exec(normalized)?.index)
    .filter((index) => index !== undefined);
  return indexes.length > 0 ? Math.min(...indexes) : -1;
};

// Kept as the public predicate name for compatibility with the test/CLI seam. It accepts
// a complete source string as well as one line so statement-level patterns can be tested.
export const lineReadsLegacyChunkVector = (source) =>
  firstLegacyChunkVectorIndex(source) >= 0;

export const findLegacyChunkVectorReaders = (srcDir) => {
  const offenders = [];
  const walk = (dir) => {
    for (const entry of readdirSync(dir)) {
      const full = join(dir, entry);
      if (statSync(full).isDirectory()) {
        walk(full);
        continue;
      }
      if (!entry.endsWith(".ts")) continue;
      const rel = relative(srcDir, full).split("\\").join("/");
      if (ALLOWLIST.has(rel) || GENERATED_FILES.has(rel)) continue;
      const source = readFileSync(full, "utf8");
      const matchIndex = firstLegacyChunkVectorIndex(source);
      if (matchIndex >= 0) {
        const lineNumber = source.slice(0, matchIndex).split("\n").length;
        const line = source.split("\n")[lineNumber - 1]?.trim() ?? "";
        offenders.push(`${rel}:${lineNumber}: ${line}`);
      }
    }
  };
  walk(srcDir);
  return offenders;
};

// CLI entry (skipped when imported by the fixture test).
if (import.meta.url === `file://${process.argv[1]}`) {
  const srcDir = fileURLToPath(new URL("../src", import.meta.url));
  const offenders = findLegacyChunkVectorReaders(srcDir);
  if (offenders.length > 0) {
    console.error("✖ New reader of the legacy chunks.embedding columns (issue #1063):");
    for (const o of offenders) console.error("  " + o);
    console.error(
      `\n${offenders.length} violation(s). Read vectors from chunk_embeddings instead — `
      + "it is the table that supports more than one embedding width. If the legacy "
      + "column is genuinely still needed, add the file to ALLOWLIST in "
      + "scripts/checkLegacyChunkVectorReaders.mjs naming the step that removes it.",
    );
    process.exit(1);
  }
  console.log(
    `✔ no new readers of the legacy chunk vector columns (${ALLOWLIST.size} allowlisted)`,
  );
}
