#!/usr/bin/env bash
#
# Generate a canonical schema snapshot for onboarding/discoverability.
#
# The migration files in backend/src/db/migrations/ remain the system of record.
# This script does NOT change how the schema is built — it produces a single,
# human-readable view of the *resulting* schema so a newcomer can read one file
# instead of replaying 90+ migrations, and so schema changes are visible in review.
#
# It is authoritative by construction: it applies every migration, in order, to a
# throwaway Postgres and dumps that, so the snapshot can never silently drift from
# the migrations. The throwaway Postgres is a container this script owns, so the
# behaviour is identical locally and in CI — the only requirement is Docker. It does
# not touch the dev database and does not need the compose stack running.
#
# Usage:
#   pnpm --dir backend run db:schema          # regenerate and write the snapshot
#   pnpm --dir backend run db:schema:check    # fail if the committed snapshot is stale (CI)

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
MIGRATIONS_DIR="$ROOT/backend/src/db/migrations"
OUT="$ROOT/backend/src/db/schema.sql"

IMAGE="pgvector/pgvector:0.8.5-pg16"
CONTAINER="radioso-schema-snapshot-$$"
DB="radioso"

CHECK=0
if [[ "${1:-}" == "--check" ]]; then
  CHECK=1
fi

cleanup() { docker rm -f "$CONTAINER" >/dev/null 2>&1 || true; }
trap cleanup EXIT

echo "Starting throwaway Postgres ($IMAGE) ..." >&2
docker run -d --name "$CONTAINER" \
  -e POSTGRES_DB="$DB" -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres \
  "$IMAGE" >/dev/null

# The official Postgres image briefly accepts connections during its init phase,
# then stops that temporary server and starts the final one. Wait for init to
# complete before trusting pg_isready, otherwise migrations can race the restart.
ready=0
for _ in $(seq 1 90); do
  if docker logs "$CONTAINER" 2>&1 | grep -q "PostgreSQL init process complete; ready for start up." \
    && docker exec "$CONTAINER" pg_isready -U postgres -d "$DB" >/dev/null 2>&1; then
    ready=1
    break
  fi
  sleep 1
done
if [[ "$ready" -ne 1 ]]; then
  echo "Throwaway Postgres did not finish initialization in time." >&2
  exit 1
fi

# client_min_messages=warning silences the IF [NOT] EXISTS drift NOTICEs migrations emit.
psql_db() {
  docker exec -i -e PGOPTIONS="-c client_min_messages=warning" \
    "$CONTAINER" psql -v ON_ERROR_STOP=1 -U postgres -d "$DB" "$@"
}

echo "Applying migrations ..." >&2
for migration in "$MIGRATIONS_DIR"/*.sql; do
  psql_db < "$migration" >/dev/null
done

snapshot="$(
  {
    echo "-- Schema snapshot — generated by backend/scripts/dump-schema.sh. DO NOT EDIT BY HAND."
    echo "-- The system of record is backend/src/db/migrations/*.sql; this is a read-only view."
    echo "-- Regenerate with: pnpm --dir backend run db:schema"
    echo ""
    # Strip the \restrict/\unrestrict guard lines: pg_dump 16.13+ embeds a random
    # nonce in them, which would make the snapshot differ on every run.
    docker exec "$CONTAINER" pg_dump \
      --schema-only --no-owner --no-privileges --no-comments \
      -U postgres -d "$DB" \
      | grep -vE '^\\(un)?restrict '
  }
)"

if [[ "$CHECK" -eq 1 ]]; then
  if ! diff -u "$OUT" <(printf '%s\n' "$snapshot"); then
    echo "" >&2
    echo "Schema snapshot is stale. Run: pnpm --dir backend run db:schema" >&2
    exit 1
  fi
  echo "Schema snapshot is up to date." >&2
else
  printf '%s\n' "$snapshot" > "$OUT"
  echo "Wrote $OUT" >&2
fi
