import { RETRIEVAL_ANSWER_ADAPTER, retrieveSkillConfigSchema } from "../../retrieval/public.js";
import type { SkillCapabilityDescriptor } from "../capabilityRegistry.js";

export const retrieveCapability: SkillCapabilityDescriptor<"retrieve", "retrieve"> = {
  id: "retrieve",
  storedKind: "retrieve",
  targetKind: "source_scope",
  requiresTarget: false,
  enumerateTargets: async () => [],
  inputSchema: {
    source: "static",
    schema: {
      fields: ["query"],
      required: ["query"],
    },
  },
  settingsFields: [
    {
      key: "sourceScope",
      label: "Source scope",
      type: "source_scope",
      help: "Choose whether this retrieve skill can search all sources or only selected sources.",
      group: "Scope",
    },
    {
      key: "instruction",
      label: "Instruction",
      type: "textarea",
      help: "Capability-specific retrieval instruction used when this skill runs.",
      group: "Scope",
    },
    {
      key: "retrievalStrategy",
      label: "Retrieval strategy",
      type: "select",
      defaultValue: "fixed",
      options: [
        { value: "fixed", label: "Fixed" },
        { value: "reasoning", label: "Reasoning" },
        { value: "auto", label: "Auto" },
      ],
      group: "Retrieval tuning",
      advanced: true,
    },
    {
      key: "vectorTopK",
      label: "Vector top K",
      type: "number",
      defaultValue: 15,
      min: 1,
      max: 300,
      group: "Retrieval tuning",
      advanced: true,
    },
    {
      key: "rerankEnabled",
      label: "Rerank results",
      type: "boolean",
      defaultValue: true,
      group: "Retrieval tuning",
      advanced: true,
    },
    {
      key: "rerankTopK",
      label: "Rerank top K",
      type: "number",
      defaultValue: 5,
      min: 1,
      max: 100,
      group: "Retrieval tuning",
      advanced: true,
    },
    {
      key: "queryRewriteEnabled",
      label: "Query rewrite",
      type: "boolean",
      defaultValue: true,
      group: "Query rewrite",
      advanced: true,
    },
    {
      key: "temporalStructuredLookupEnabled",
      label: "Temporal structured lookup",
      type: "boolean",
      defaultValue: true,
      help: "When someone asks for upcoming events without naming one, also fetch documents by their extracted event dates instead of relying on text similarity alone. Needs AI document enrichment on the knowledge base.",
      group: "Temporal retrieval",
      advanced: true,
    },
    {
      key: "temporalBoostUpcomingEnabled",
      label: "Upcoming event boost",
      type: "boolean",
      defaultValue: true,
      help: "Rank documents about ongoing or upcoming events above past ones when the question is about event dates.",
      group: "Temporal retrieval",
      advanced: true,
    },
    {
      key: "temporalDeterministicSortEnabled",
      label: "Deterministic temporal sort",
      type: "boolean",
      defaultValue: true,
      help: "Present event evidence in date order (soonest first) for event-date questions, instead of relying on the model to order them.",
      group: "Temporal retrieval",
      advanced: true,
    },
    {
      key: "semanticRewriteInstructions",
      label: "Semantic rewrite instructions",
      type: "textarea",
      group: "Query rewrite",
      advanced: true,
    },
    {
      key: "lexicalRewriteInstructions",
      label: "Lexical rewrite instructions",
      type: "textarea",
      group: "Query rewrite",
      advanced: true,
    },
    {
      key: "suggestedQuestionsEnabled",
      label: "Suggested questions",
      type: "boolean",
      defaultValue: true,
      group: "Suggested questions",
    },
    {
      key: "suggestedQuestionsCount",
      label: "Suggested questions count",
      type: "number",
      defaultValue: 3,
      min: 1,
      max: 4,
      group: "Suggested questions",
      advanced: true,
    },
  ],
  outcomeVocabulary: ["found", "empty"],
  supportedInvocationModes: ["default_answer", "routine_named", "agent_selectable"],
  defaultInvocationMode: "default_answer",
  executorAdapter: RETRIEVAL_ANSWER_ADAPTER,
  configSchema: retrieveSkillConfigSchema,
  validateConfig: (config) => retrieveSkillConfigSchema.safeParse(config),
};
