import { RETRIEVAL_ANSWER_ADAPTER, retrieveSkillConfigSchema } from "../../retrieval/public.js";
import { defaultRetrievalSettings } from "../../settings/contracts/retrieval.js";
import type { SkillCapabilityDescriptor } from "../capabilityRegistry.js";

// Only the per-field defaults are read from this record; the workspaceId it
// embeds never leaves this module, so a placeholder is safe here.
const retrieveSettingsDefaults = defaultRetrievalSettings("__retrieve_capability_descriptor__");

export const retrieveCapability: SkillCapabilityDescriptor<"retrieve", "retrieve"> = {
  id: "retrieve",
  storedKind: "retrieve",
  targetKind: "source_scope",
  requiresTarget: false,
  enumerateTargets: async () => [],
  inputSchema: {
    source: "static",
    schema: {
      fields: ["query"],
      required: ["query"],
    },
  },
  settingsFields: [
    {
      key: "sourceScope",
      label: "Source scope",
      type: "source_scope",
      help: "Choose whether this retrieve skill can search all sources or only selected sources.",
      group: "Scope",
    },
    {
      key: "instruction",
      label: "Instruction",
      type: "textarea",
      help: "Capability-specific retrieval instruction used when this skill runs.",
      group: "Scope",
    },
    {
      key: "retrievalStrategy",
      label: "Retrieval strategy",
      type: "select",
      help: "Fixed runs one search pass. Reasoning lets the model plan and run multiple searches. Auto picks per query.",
      defaultValue: retrieveSettingsDefaults.retrievalStrategy,
      options: [
        { value: "fixed", label: "Fixed" },
        { value: "reasoning", label: "Reasoning" },
        { value: "auto", label: "Auto" },
      ],
      group: "Retrieval tuning",
      advanced: true,
    },
    {
      key: "vectorTopK",
      label: "Vector top K",
      type: "number",
      help: "How many chunks are fetched from the vector index before filtering and reranking.",
      defaultValue: retrieveSettingsDefaults.vectorTopK,
      min: 1,
      max: 300,
      group: "Retrieval tuning",
      advanced: true,
    },
    {
      key: "rerankEnabled",
      label: "Rerank results",
      type: "boolean",
      help: "Re-score the fetched chunks with a reranker model to improve ordering.",
      defaultValue: retrieveSettingsDefaults.rerankEnabled,
      group: "Retrieval tuning",
      advanced: true,
    },
    {
      key: "rerankTopK",
      label: "Rerank top K",
      type: "number",
      help: "How many chunks survive reranking and are passed to the answer.",
      defaultValue: retrieveSettingsDefaults.rerankTopK,
      dependsOnKey: "rerankEnabled",
      min: 1,
      max: 100,
      group: "Retrieval tuning",
      advanced: true,
    },
    {
      key: "queryRewriteEnabled",
      label: "Query rewrite",
      type: "boolean",
      help: "Rewrite the user message into search queries before retrieval.",
      defaultValue: retrieveSettingsDefaults.queryRewriteEnabled,
      group: "Query rewrite",
      advanced: true,
    },
    {
      key: "temporalStructuredLookupEnabled",
      label: "Temporal structured lookup",
      type: "boolean",
      defaultValue: retrieveSettingsDefaults.temporalStructuredLookupEnabled,
      help: "When someone asks for upcoming events without naming one, also fetch documents by their extracted event dates instead of relying on text similarity alone. Needs metadata extraction enabled on the knowledge base.",
      group: "Temporal retrieval",
      advanced: true,
    },
    {
      key: "temporalBoostUpcomingEnabled",
      label: "Upcoming event boost",
      type: "boolean",
      defaultValue: retrieveSettingsDefaults.temporalBoostUpcomingEnabled,
      help: "Rank documents about ongoing or upcoming events above past ones when the question is about event dates.",
      group: "Temporal retrieval",
      advanced: true,
    },
    {
      key: "temporalDeterministicSortEnabled",
      label: "Deterministic temporal sort",
      type: "boolean",
      defaultValue: retrieveSettingsDefaults.temporalDeterministicSortEnabled,
      help: "Present event evidence in date order (soonest first) for event-date questions, instead of relying on the model to order them.",
      group: "Temporal retrieval",
      advanced: true,
    },
    {
      key: "semanticRewriteInstructions",
      label: "Semantic rewrite instructions",
      type: "textarea",
      help: "Instructions used to rewrite the user message into the semantic (vector) search query. Replaces the default; leave empty to keep the default shown.",
      defaultValue: retrieveSettingsDefaults.semanticRewriteInstructions,
      dependsOnKey: "queryRewriteEnabled",
      group: "Query rewrite",
      advanced: true,
    },
    {
      key: "lexicalRewriteInstructions",
      label: "Lexical rewrite instructions",
      type: "textarea",
      help: "Instructions used to rewrite the user message into the lexical (keyword) search query. Replaces the default; leave empty to keep the default shown.",
      defaultValue: retrieveSettingsDefaults.lexicalRewriteInstructions,
      dependsOnKey: "queryRewriteEnabled",
      group: "Query rewrite",
      advanced: true,
    },
    {
      key: "suggestedQuestionsEnabled",
      label: "Suggested questions",
      type: "boolean",
      help: "Offer follow-up question suggestions after each answer.",
      defaultValue: retrieveSettingsDefaults.suggestedQuestionsEnabled,
      group: "Suggested questions",
    },
    {
      key: "suggestedQuestionsCount",
      label: "Suggested questions count",
      type: "number",
      help: "How many follow-up questions to suggest.",
      defaultValue: retrieveSettingsDefaults.suggestedQuestionsCount,
      dependsOnKey: "suggestedQuestionsEnabled",
      min: 1,
      max: 4,
      group: "Suggested questions",
    },
  ],
  outcomeVocabulary: ["found", "empty"],
  supportedInvocationModes: ["default_answer", "routine_named", "agent_selectable"],
  defaultInvocationMode: "default_answer",
  executorAdapter: RETRIEVAL_ANSWER_ADAPTER,
  configSchema: retrieveSkillConfigSchema,
  validateConfig: (config) => retrieveSkillConfigSchema.safeParse(config),
};
