/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AbuseControlEntries {
  attempt_count: Generated<number>;
  blocked_until: Timestamp | null;
  created_at: Generated<Timestamp>;
  scope: string;
  subject_key: string;
  updated_at: Generated<Timestamp>;
  window_started_at: Timestamp;
}

export interface AccountInvitations {
  accepted_at: Timestamp | null;
  accepted_by_user_id: string | null;
  account_id: string;
  created_at: Generated<Timestamp>;
  email: string;
  expires_at: Timestamp;
  id: string;
  invited_by_membership_id: string;
  role: Generated<string>;
  status: string;
  token_hash: string;
  updated_at: Generated<Timestamp>;
}

export interface AccountMemberships {
  account_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  role: string;
  status: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Accounts {
  created_at: Generated<Timestamp>;
  email: string;
  id: string;
  name: string;
  password_hash: string;
  updated_at: Generated<Timestamp>;
}

export interface AgentAccessGrants {
  agent_id: string;
  channel: Generated<string>;
  created_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  encrypted_token: string;
  expires_at: Timestamp | null;
  id: Generated<string>;
  label: string | null;
  last_used_at: Timestamp | null;
  origin_allowlist: Generated<string[]>;
  origin_mode: string;
  principal_kind: string;
  revoked_at: Timestamp | null;
  role: Generated<string>;
  token_hash: string;
  token_prefix: string;
  workspace_id: string;
}

export interface AgentContextVariables {
  agent_id: string;
  created_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  id: Generated<string>;
  max_age_seconds: number | null;
  resolver_skill_id: string | null;
  resolver_timeout_ms: number | null;
  source: string;
  surfacing: string;
  updated_at: Generated<Timestamp>;
  variable_id: string;
}

export interface AgentDirectives {
  action: string;
  agent_id: string;
  binding: Json | null;
  condition_description: string | null;
  condition_kind: string;
  created_at: Generated<Timestamp>;
  depends_on: Generated<string[]>;
  description: string | null;
  excludes: Generated<string[]>;
  id: Generated<string>;
  lifecycle: Json | null;
  metadata: Generated<Json>;
  name: string;
  priority: number | null;
  required_capabilities: Generated<string[]>;
  routes: Generated<string[]>;
  scope_tags: Generated<string[]>;
  updated_at: Generated<Timestamp>;
}

export interface AgentDocumentSources {
  agent_id: string;
  created_at: Generated<Timestamp>;
  source_id: string | null;
}

export interface Agents {
  behavior_settings: Generated<Json>;
  chat_model: string | null;
  chat_provider: string | null;
  created_at: Generated<Timestamp>;
  greeting_settings: Generated<Json>;
  id: Generated<string>;
  internal_name: Generated<string>;
  name: Generated<string>;
  output_modes: Generated<Json>;
  retrieval_enabled: Generated<boolean>;
  skill_settings: Generated<Json>;
  source_scope_mode: Generated<string>;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface AgentSkills {
  agent_id: string;
  config: Generated<Json>;
  created_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  id: string;
  invocation_mode: Generated<string>;
  kind: string;
  skill_name: string;
  target_id: string | null;
  target_type: string | null;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface AssistantAnswerFeedback {
  account_id: string | null;
  actor_id: string;
  actor_type: string;
  anonymous_session_id: string | null;
  assistant_message_id: string;
  comment: string | null;
  conversation_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  updated_at: Generated<Timestamp>;
  user_id: string | null;
  value: string;
  workspace_id: string;
}

export interface AssistantAnswerTriage {
  assistant_message_id: string;
  closed_at: Timestamp | null;
  reason: string | null;
  resolution_note: string | null;
  resolution_reason: string | null;
  state: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
  workspace_id: string;
}

export interface AssistantAnswerTriageTransitions {
  actor_id: string | null;
  assistant_message_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  linked_eval_case_id: string | null;
  next_state: string;
  prior_state: string;
  resolution_reason: string | null;
  resulting_version: number;
  workspace_id: string;
}

export interface AudiencePulseSnapshots {
  created_at: Generated<Timestamp>;
  generated_at: Timestamp;
  period_end: Timestamp;
  period_start: Timestamp;
  prompt_evidence_refs: Json;
  report: Json;
  revision: string;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface AuditEvents {
  account_id: string | null;
  created_at: Generated<Timestamp>;
  event_status: string;
  event_type: string;
  id: string;
  metadata_json: Generated<Json>;
  workspace_id: string | null;
}

export interface BootstrapGreetingCache {
  agent_id: string;
  created_at: Generated<Timestamp>;
  fingerprint: string;
  greeting_text: string;
  id: string;
  locale_used: string | null;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface ChunkEmbeddings {
  canonical_version: Int8;
  chunk_id: string;
  content_hash: string;
  created_at: Generated<Timestamp>;
  dimensions: number;
  document_revision: number;
  embedding: string;
  embedding_space_id: string;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface Chunks {
  chunk_index: number;
  content: string;
  created_at: Generated<Timestamp>;
  date_from: Timestamp | null;
  date_to: Timestamp | null;
  document_id: string;
  embedding: string | null;
  embedding_model: Generated<string>;
  embedding_unbounded: string | null;
  end_offset: number | null;
  id: string;
  metadata: Generated<Json>;
  search_text: string | null;
  start_offset: number | null;
  token_count: number | null;
  workspace_id: string;
}

export interface ClarificationStates {
  asked_event_id: string | null;
  candidates: Generated<Json>;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  mode: Generated<string>;
  original_query: string | null;
  session_id: string;
  source: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface ConnectorConfigs {
  config_data: Generated<Json>;
  connector_id: string;
  created_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  error_status: string | null;
  id: Generated<string>;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface ConnectorMigrations {
  applied_at: Generated<Timestamp>;
  connector_id: string;
  id: Generated<string>;
  migration_name: string;
}

export interface ConnectorSyncState {
  backfill_completed_at: Timestamp | null;
  connector_id: string;
  last_error: string | null;
  last_ingested_count: number | null;
  last_modified_at: Timestamp | null;
  last_run_at: Timestamp | null;
  sync_lock_token: string | null;
  sync_requested_at: Timestamp | null;
  sync_started_at: Timestamp | null;
  workspace_id: string;
}

export interface ConnectorWhatsappContacts {
  conversation_id: string;
  first_seen_at: Generated<Timestamp>;
  id: Generated<string>;
  last_message_at: Generated<Timestamp>;
  profile_name: string | null;
  wa_id: string;
  workspace_id: string;
}

export interface ConnectorWhatsappMessageLog {
  created_at: Generated<Timestamp>;
  direction: string;
  error_details: string | null;
  id: Generated<string>;
  message_type: string;
  payload: Json;
  status: string;
  wa_id: string;
  wamid: string;
  workspace_id: string;
}

export interface ContextIdentityNonces {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  nonce: string;
  workspace_id: string;
}

export interface ContextVariables {
  created_at: Generated<Timestamp>;
  default_surfacing: string;
  description: string | null;
  id: Generated<string>;
  name: string;
  sensitivity: string;
  trust_tier: string;
  updated_at: Generated<Timestamp>;
  value_type: string;
  workspace_id: string;
}

export interface ContextVariableValues {
  data: Json;
  id: Generated<string>;
  last_modified: Generated<Timestamp>;
  scope_id: string;
  scope_type: string;
  variable_id: string;
  workspace_id: string;
}

export interface ConversationOwnership {
  conversation_id: string;
  created_at: Generated<Timestamp>;
  owner_account_id: string | null;
  owner_display_name: string | null;
  reason: string | null;
  state: string;
  taken_over_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
  workspace_id: string;
}

export interface Conversations {
  agent_id: string | null;
  anonymous_session_id: string | null;
  channel_context: Json | null;
  created_at: Generated<Timestamp>;
  entry_page_url: string | null;
  id: string;
  source_channel: string | null;
  source_origin: string | null;
  updated_at: Generated<Timestamp>;
  verified_customer_id: string | null;
  workspace_id: string;
}

export interface ConversationSummaries {
  covered_message_count: number;
  covered_through: Timestamp;
  expires_at: Timestamp;
  session_id: string;
  summary: string;
  updated_at: Generated<Timestamp>;
}

export interface DirectiveStates {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp | null;
  firings: Generated<Json>;
  session_id: string;
  turn_seq: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface DocumentProcessingJobs {
  attempt_count: Generated<number>;
  available_at: Generated<Timestamp>;
  claimed_at: Timestamp | null;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  document_id: string;
  document_revision: number;
  embedding_space_id: string | null;
  id: string;
  kind: Generated<string>;
  last_error: string | null;
  options: Json | null;
  status: string;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
  workspace_profile_generation: Int8 | null;
}

export interface Documents {
  content_hash: string | null;
  content_size_bytes: Int8 | null;
  created_at: Generated<Timestamp>;
  enrichment: Json | null;
  external_document_id: string | null;
  failed_at: Timestamp | null;
  failure_reason: string | null;
  id: string;
  markdown_content: string;
  metadata: Generated<Json>;
  retrieval_enabled: Generated<boolean>;
  retrieval_expires_at: Timestamp | null;
  revision: Generated<number>;
  source_content: string;
  source_filename: string | null;
  source_id: string | null;
  source_kind: Generated<string>;
  source_mime_type: string | null;
  source_size_bytes: number | null;
  source_storage_bucket: string | null;
  source_storage_generation: string | null;
  source_storage_object: string | null;
  status: string;
  title: string;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface DocumentSources {
  config: Generated<Json>;
  created_at: Generated<Timestamp>;
  external_id: string | null;
  id: Generated<string>;
  kind: string;
  last_sync_status: string | null;
  last_synced_at: Timestamp | null;
  metadata: Generated<Json>;
  name: string;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface EmailSkillActivity {
  agent_id: string;
  connection_id: string;
  conversation_id: string | null;
  created_at: Generated<Timestamp>;
  error_code: string | null;
  id: string;
  mode: string;
  outcome: string;
  provider_message_id: string | null;
  recipient_summary: Generated<Json>;
  routine_id: string | null;
  skill_definition_id: string;
  skill_name: string;
  workspace_id: string;
}

export interface EmailVerificationTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  request_ip: string | null;
  request_user_agent: string | null;
  token_hash: string;
  used_at: Timestamp | null;
  user_id: string;
}

export interface EmbeddingSpaces {
  created_at: Generated<Timestamp>;
  dimensions: number;
  distance_metric: string;
  document_task: string | null;
  endpoint_scope_fingerprint: string;
  id: string;
  identity_fingerprint: string;
  model: string;
  model_version: string | null;
  normalization: string;
  provider: string;
  quarantine_reason: string | null;
  query_task: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  vector_options: Generated<Json>;
}

export interface EmbeddingUsageItems {
  chunk_id: string | null;
  chunk_index: number;
  content_bytes: Int8;
  document_id: string;
  document_revision: number;
  estimated_tokens: Int8 | null;
  usage_event_id: string;
}

export interface EvalCases {
  assertions: Generated<Json>;
  created_at: Generated<Timestamp>;
  id: string;
  last_run_id: string | null;
  name: string;
  snapshot_id: string;
  status: string;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface EvalMessageCaseAssociations {
  assistant_message_id: string;
  case_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  workspace_id: string;
}

export interface EvalRuns {
  assertion_verdicts: Generated<Json>;
  case_id: string | null;
  completed_at: Timestamp | null;
  id: string;
  mode: string;
  observed_output: Generated<Json>;
  outcome_reason: string | null;
  overrides: Generated<Json>;
  resolved_config: Generated<Json>;
  snapshot_id: string;
  started_at: Generated<Timestamp>;
  status: string;
  workspace_id: string;
}

export interface EvalSnapshots {
  captured_at: Generated<Timestamp>;
  captured_by: string | null;
  fidelity: string;
  id: string;
  messages: Json;
  original_agent: Json | null;
  original_agent_config: Json | null;
  original_conversation_summary: Json | null;
  original_instruction_block: Json | null;
  original_model_id: string | null;
  original_retrieval_result: Json | null;
  original_retrieval_settings: Json | null;
  original_routine_state: Json | null;
  replay_target: Json | null;
  source_agent_id: string | null;
  source_conversation_id: string;
  source_message_id: string | null;
  workspace_id: string;
}

export interface FacetExtractionJobs {
  attempt_count: Generated<number>;
  claimed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  last_error: string | null;
  message_id: string;
  scheduled_at: Generated<Timestamp>;
  status: string;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface IngestionSettings {
  chunking_strategy: Generated<string>;
  created_at: Generated<Timestamp>;
  document_enrichment_enabled: Generated<boolean>;
  embedding_model: Generated<string>;
  fixed_window_chunk_overlap: Generated<number>;
  fixed_window_chunk_size: Generated<number>;
  pending_embedding_model: string | null;
  revision: Generated<Int8>;
  structured_max_chunk_size: Generated<number>;
  structured_min_chunk_size: Generated<number>;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface IntegrationConnections {
  account_id: string | null;
  config: Generated<Json>;
  created_at: Generated<Timestamp>;
  display_name: string;
  id: string;
  last_error_code: string | null;
  last_health_checked_at: Timestamp | null;
  last_health_status: string | null;
  oauth_connection_id: string;
  provider: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface IntegrationOauthConnections {
  created_at: Generated<Timestamp>;
  credential_ciphertext: string | null;
  display_name: string;
  encryption_key_id: string | null;
  granted_scopes: Generated<string[]>;
  id: string;
  last_error_code: string | null;
  last_refresh_at: Timestamp | null;
  oauth_client_ciphertext: string | null;
  oauth_flow_ciphertext: string | null;
  provider: string;
  provider_account_id: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface McpConnections {
  agent_id: string;
  auth_method: string;
  created_at: Generated<Timestamp>;
  credential_ciphertext: string | null;
  display_name: string;
  encryption_key_id: string | null;
  id: string;
  oauth_client_ciphertext: string | null;
  oauth_flow_ciphertext: string | null;
  server_url: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface MessageFacets {
  created_at: Generated<Timestamp>;
  dimensions: number | null;
  embedding: string | null;
  embedding_profile_id: string | null;
  facet_text: string;
  message_id: string;
  prompt_version: string;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface Messages {
  content: string;
  conversation_id: string;
  created_at: Generated<Timestamp>;
  grounding_claim_count: number | null;
  grounding_invalid_source_count: number | null;
  grounding_sourced_claim_count: number | null;
  grounding_unsourced_claim_count: number | null;
  grounding_verdict: string | null;
  id: string;
  metadata_json: Generated<Json>;
  role: string;
  skill_name: string | null;
  skill_outcome: string | null;
  skill_status: string | null;
  source: string | null;
  total_latency_ms: number | null;
  workspace_id: string;
}

export interface PasswordResetTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  request_ip: string | null;
  request_user_agent: string | null;
  token_hash: string;
  used_at: Timestamp | null;
  user_id: string;
}

export interface PendingDecisions {
  agent_id: string;
  content_hash: string;
  conversation_id: string;
  created_at: Generated<Timestamp>;
  deadline: Timestamp | null;
  decided_at: Timestamp | null;
  decided_by: string | null;
  decider_scope: Json;
  decision: Json | null;
  handle: string;
  id: Generated<string>;
  options: Generated<Json>;
  reason: string | null;
  routine_id: string;
  session_id: string;
  status: Generated<string>;
  step_id: string;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface RetrievalSettings {
  chat_model: string | null;
  chat_provider: string | null;
  chunking_strategy: Generated<string>;
  created_at: Generated<Timestamp>;
  rerank_model: string | null;
  rerank_provider: string | null;
  rewrite_model: string | null;
  rewrite_provider: string | null;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface RoutineActionRequests {
  account_id: string | null;
  attempts: Generated<number>;
  conversation_id: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  idempotency_key: string | null;
  last_error: string | null;
  next_attempt_at: Timestamp | null;
  payload: Generated<Json>;
  status: Generated<string>;
  type: string;
  updated_at: Generated<Timestamp>;
  workspace_id: string | null;
}

export interface RoutineCompletionExport {
  created_at: Generated<Timestamp>;
  definition_id: string;
  destination_ref: string;
  enabled: Generated<boolean>;
  trigger_kinds: Generated<string[]>;
  updated_at: Generated<Timestamp>;
}

export interface RoutineDefinition {
  activation_gate_ref: string | null;
  activation_priority: Generated<number>;
  activation_reentry_mode: Generated<string>;
  activation_trigger_description: string;
  agent_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  lineage_id: string;
  name: string;
  status: string;
  trigger_embedding: string | null;
  trigger_embedding_hash: string | null;
  trigger_embedding_model: string | null;
  updated_at: Generated<Timestamp>;
  version: number;
}

export interface RoutineSlot {
  definition_id: string;
  description: string | null;
  key: string;
  mutable: Generated<boolean>;
  ordinal: number;
  required: Generated<boolean>;
  stable_slot_id: string;
  type: string;
}

export interface RoutineStates {
  attempts: Generated<Json>;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp | null;
  path: Generated<string[]>;
  routine_id: string;
  session_id: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  variables: Generated<Json>;
}

export interface RoutineStep {
  action_type: string | null;
  capture_key: string | null;
  definition_id: string;
  instruction: string;
  kind: string;
  metadata: Generated<Json>;
  options: Json | null;
  ordinal: number;
  stable_step_id: string;
  tool_ref: string | null;
}

export interface RoutineTerminal {
  action_type: string | null;
  definition_id: string;
  instruction: string | null;
  kind: string;
  ordinal: number;
  stable_step_id: string;
}

export interface RoutineTransition {
  counter_limit: number | null;
  definition_id: string;
  field_op: string | null;
  field_ref: string | null;
  field_unit: string | null;
  field_value: Json | null;
  field_values: Json | null;
  from_step: string;
  guard_kind: string;
  guard_text: string | null;
  ordinal: number;
  outcome_status: string | null;
  to_ref: string;
}

export interface Sessions {
  account_id: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  last_seen_at: Generated<Timestamp>;
  revoked_at: Timestamp | null;
  session_token_hash: string;
  user_id: string;
}

export interface SkillIntakeStates {
  collected: Generated<Json>;
  conversation_id: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp | null;
  id: string;
  invalid: Generated<Json>;
  last_prompted_field: string | null;
  missing: Generated<string[]>;
  skill_name: string;
  status: string;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface SlackChannelBindings {
  answering_agent_id: string;
  channel_id: string | null;
  created_at: Generated<Timestamp>;
  escalation_channel_id: string | null;
  gap_escalation_enabled: Generated<boolean>;
  id: string;
  installation_id: string;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface SlackConversationLinks {
  conversation_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  installation_id: string;
  slack_key: string;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface SlackInboundEvents {
  event_id: string;
  received_at: Generated<Timestamp>;
  status: Generated<string>;
  team_id: string;
}

export interface SlackInstallations {
  account_id: string;
  bot_user_id: string;
  connection_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  team_id: string;
  team_name: string | null;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface TopicCensusRuns {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  params_json: Json;
  question_count: number;
  seed: string;
  unclassified_count: Generated<number>;
  window_end: Timestamp;
  window_start: Timestamp;
  workspace_id: string;
}

export interface TopicMemberships {
  distance: number;
  message_id: string;
  run_id: string;
  topic_id: string;
  workspace_id: string;
}

export interface Topics {
  centroid: string;
  created_at: Generated<Timestamp>;
  created_run_id: string;
  description: string;
  dimensions: number;
  dissolved_at: Timestamp | null;
  id: Generated<string>;
  last_seen_run_id: string;
  radius: number;
  title: string;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface TopicTransitions {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: string;
  parent_topic_ids: Generated<string[]>;
  run_id: string;
  topic_id: string;
  via_centroid_fallback: Generated<boolean>;
  workspace_id: string;
}

export interface UsageDailyRollups {
  account_id: string;
  input_bytes: Generated<Int8>;
  input_tokens: Generated<Int8>;
  model: string;
  operation: string;
  output_bytes: Generated<Int8>;
  output_tokens: Generated<Int8>;
  provider: string;
  total_tokens: Generated<Int8>;
  usage_date: Timestamp;
  vector_count: Generated<Int8>;
}

export interface UsageEvents {
  account_id: string | null;
  agent_id: string | null;
  conversation_id: string | null;
  created_at: Generated<Timestamp>;
  document_id: string | null;
  document_revision: number | null;
  error_code: string | null;
  event_kind: Generated<string>;
  id: string;
  idempotency_key: string;
  input_bytes: Generated<Int8>;
  input_tokens: Generated<Int8>;
  job_id: string | null;
  message_id: string | null;
  model: string;
  occurred_at: Generated<Timestamp>;
  operation: string;
  output_bytes: Generated<Int8>;
  output_tokens: Generated<Int8>;
  provider: string;
  provider_request_id: string | null;
  reasoning_tokens: Int8 | null;
  source_id: string | null;
  status: string;
  surface: string;
  total_tokens: Generated<Int8>;
  usage_quality: string;
  vector_count: Generated<number>;
  workspace_id: string | null;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  email_verified_at: Timestamp | null;
  id: string;
  password_hash: string;
  updated_at: Generated<Timestamp>;
}

export interface VectorIndexCheckpoints {
  acknowledged_sequence: Generated<Int8>;
  backend_key: string;
  embedding_space_id: string;
  readiness: Generated<string>;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface VectorIndexWork {
  attempt_count: Generated<number>;
  available_at: Generated<Timestamp>;
  canonical_version: Int8;
  chunk_id: string;
  claimed_at: Timestamp | null;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  document_id: string | null;
  embedding_space_id: string;
  id: string;
  last_error: string | null;
  operation: string;
  payload: Generated<Json>;
  sequence: Generated<Int8>;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface WebsiteCrawlJobs {
  account_id: string | null;
  attempt_count: Generated<number>;
  available_at: Generated<Timestamp>;
  checkpoint_json: Generated<Json>;
  claimed_at: Timestamp | null;
  completed_at: Timestamp | null;
  crawl_limit: number;
  created_at: Generated<Timestamp>;
  id: string;
  last_error: string | null;
  policy_json: Generated<Json>;
  requested_url: string;
  result_json: Json | null;
  resume_requested_at: Timestamp | null;
  source_id: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface WorkspaceEmbeddingProfiles {
  active_embedding_space_id: string;
  created_at: Generated<Timestamp>;
  generation: Generated<Int8>;
  pending_embedding_space_id: string | null;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface WorkspaceEmbeddingTransitions {
  cleanup_after: Timestamp | null;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  failure_reason: string | null;
  generation: Int8;
  id: string;
  source_embedding_space_id: string;
  status: string;
  target_embedding_space_id: string;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface WorkspaceGrants {
  account_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  role: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
  workspace_id: string;
}

export interface WorkspaceProviderCredentials {
  ciphertext: string;
  created_at: Generated<Timestamp>;
  provider: string;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface Workspaces {
  account_id: string;
  anonymous_chat_enabled: Generated<boolean>;
  anonymous_chat_token: string | null;
  anonymous_rate_limit: Generated<number>;
  assistant_default_locale: string | null;
  assistant_name: Generated<string>;
  created_at: Generated<Timestamp>;
  default_agent_id: string | null;
  greeting_instruction: Generated<string>;
  id: Generated<string>;
  name: string;
  proactive_greeting_enabled: Generated<boolean>;
  public_route_key: string;
  updated_at: Generated<Timestamp>;
  website_embed_allowed_origins: Generated<string[]>;
  website_embed_enabled: Generated<boolean>;
  website_embed_launcher_icon: Generated<string>;
  website_embed_launcher_label: Generated<string>;
  website_embed_launcher_position: Generated<string>;
  website_embed_token: string | null;
}

export interface WorkspaceTokens {
  account_id: string;
  created_at: Generated<Timestamp>;
  encrypted_token: string;
  id: Generated<string>;
  last_used_at: Timestamp | null;
  revoked_at: Timestamp | null;
  token_hash: string;
  token_prefix: string;
  workspace_id: string;
}

export interface WorkspaceWebhookDestinations {
  created_at: Generated<Timestamp>;
  encryption_key_id: string;
  id: Generated<string>;
  last_delivery_at: Timestamp | null;
  last_delivery_status: string | null;
  name: string;
  secret_ciphertext: string;
  updated_at: Generated<Timestamp>;
  url: string;
  workspace_id: string;
}

export interface DB {
  abuse_control_entries: AbuseControlEntries;
  account_invitations: AccountInvitations;
  account_memberships: AccountMemberships;
  accounts: Accounts;
  agent_access_grants: AgentAccessGrants;
  agent_context_variables: AgentContextVariables;
  agent_directives: AgentDirectives;
  agent_document_sources: AgentDocumentSources;
  agent_skills: AgentSkills;
  agents: Agents;
  assistant_answer_feedback: AssistantAnswerFeedback;
  assistant_answer_triage: AssistantAnswerTriage;
  assistant_answer_triage_transitions: AssistantAnswerTriageTransitions;
  audience_pulse_snapshots: AudiencePulseSnapshots;
  audit_events: AuditEvents;
  bootstrap_greeting_cache: BootstrapGreetingCache;
  chunk_embeddings: ChunkEmbeddings;
  chunks: Chunks;
  clarification_states: ClarificationStates;
  connector_configs: ConnectorConfigs;
  connector_migrations: ConnectorMigrations;
  connector_sync_state: ConnectorSyncState;
  connector_whatsapp_contacts: ConnectorWhatsappContacts;
  connector_whatsapp_message_log: ConnectorWhatsappMessageLog;
  context_identity_nonces: ContextIdentityNonces;
  context_variable_values: ContextVariableValues;
  context_variables: ContextVariables;
  conversation_ownership: ConversationOwnership;
  conversation_summaries: ConversationSummaries;
  conversations: Conversations;
  directive_states: DirectiveStates;
  document_processing_jobs: DocumentProcessingJobs;
  document_sources: DocumentSources;
  documents: Documents;
  email_skill_activity: EmailSkillActivity;
  email_verification_tokens: EmailVerificationTokens;
  embedding_spaces: EmbeddingSpaces;
  embedding_usage_items: EmbeddingUsageItems;
  eval_cases: EvalCases;
  eval_message_case_associations: EvalMessageCaseAssociations;
  eval_runs: EvalRuns;
  eval_snapshots: EvalSnapshots;
  facet_extraction_jobs: FacetExtractionJobs;
  ingestion_settings: IngestionSettings;
  integration_connections: IntegrationConnections;
  integration_oauth_connections: IntegrationOauthConnections;
  mcp_connections: McpConnections;
  message_facets: MessageFacets;
  messages: Messages;
  password_reset_tokens: PasswordResetTokens;
  pending_decisions: PendingDecisions;
  retrieval_settings: RetrievalSettings;
  routine_action_requests: RoutineActionRequests;
  routine_completion_export: RoutineCompletionExport;
  routine_definition: RoutineDefinition;
  routine_slot: RoutineSlot;
  routine_states: RoutineStates;
  routine_step: RoutineStep;
  routine_terminal: RoutineTerminal;
  routine_transition: RoutineTransition;
  sessions: Sessions;
  skill_intake_states: SkillIntakeStates;
  slack_channel_bindings: SlackChannelBindings;
  slack_conversation_links: SlackConversationLinks;
  slack_inbound_events: SlackInboundEvents;
  slack_installations: SlackInstallations;
  topic_census_runs: TopicCensusRuns;
  topic_memberships: TopicMemberships;
  topic_transitions: TopicTransitions;
  topics: Topics;
  usage_daily_rollups: UsageDailyRollups;
  usage_events: UsageEvents;
  users: Users;
  vector_index_checkpoints: VectorIndexCheckpoints;
  vector_index_work: VectorIndexWork;
  website_crawl_jobs: WebsiteCrawlJobs;
  workspace_embedding_profiles: WorkspaceEmbeddingProfiles;
  workspace_embedding_transitions: WorkspaceEmbeddingTransitions;
  workspace_grants: WorkspaceGrants;
  workspace_provider_credentials: WorkspaceProviderCredentials;
  workspace_tokens: WorkspaceTokens;
  workspace_webhook_destinations: WorkspaceWebhookDestinations;
  workspaces: Workspaces;
}
