import type { AccountPermission } from "../../../modules/account/public.js";

/** HTTP-owned authorization requirements for one-to-one Ray parity checks. */
export const operationPermissionRequirements: Readonly<Record<string, readonly AccountPermission[]>> = {
  listEvalCases: ["workspace.retrieval.query"],
  getOrCreateEvalCaseBySourceMessage: ["workspace.retrieval.query"],
  runEvalCases: ["workspace.retrieval.query"],
  createEvalRun: ["workspace.retrieval.query"],
  searchRetrievalEvidence: ["workspace.retrieval.query"],
  validateAgentRoutine: ["workspace.agents.read"],
  createAssistantChatResponse: ["workspace.chat.use"],
  createAgentRoutine: ["workspace.agents.manage"],
  updateAgentRoutine: ["workspace.agents.manage"],
  reviseAgentRoutine: ["workspace.agents.manage"],
  publishAgentRoutine: ["workspace.agents.manage"],
  archiveAgentRoutine: ["workspace.agents.manage"],
  restoreAgentRoutine: ["workspace.agents.manage"],
  updateAgent: ["workspace.agents.manage"],
  analyzeWebsiteForAgentWizard: ["workspace.agents.manage"],
  createAgentFromWizard: ["workspace.agents.manage"],
  createAgentDirective: ["workspace.agents.manage"],
  updateAgentDirective: ["workspace.agents.manage"],
  deleteAgentDirective: ["workspace.agents.manage"],
  recrawlDocumentSource: ["workspace.documents.manage"],
  reprocessDocumentSource: ["workspace.documents.manage"],
  reprocessDocument: ["workspace.documents.manage"],
  createDocument: ["workspace.documents.manage"],
  updateDocumentRetrieval: ["workspace.documents.manage"],
  deleteDocument: ["workspace.documents.manage"],
  updateIngestionSettings: ["workspace.settings.manage"],
  crawlWebsiteDocuments: ["workspace.documents.manage"],
};
