import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";

const moduleUrl = new URL("../../../scripts/sync-ee-frontend-routes.mjs", import.meta.url);
const manifestModuleUrl = new URL("../../../scripts/enterprise-feature-manifests.mjs", import.meta.url);
const {
  buildGeneratedRouteFiles,
  disableEnterpriseFrontendRoutes,
  enableEnterpriseFrontendRoutes,
} = await import(moduleUrl.href) as any;
const {
  validateFeatureManifests,
} = await import(manifestModuleUrl.href) as any;

let tempRoot: string | null = null;

afterEach(async () => {
  if (tempRoot) {
    await fs.rm(tempRoot, { recursive: true, force: true });
    tempRoot = null;
  }
});

describe("Enterprise frontend route sync", () => {
  it("builds generated route stubs from manifest route contributions", () => {
    const files = buildGeneratedRouteFiles([
      {
        relativePath: "app/reset-password/page.tsx",
        packageName: "@radioso/enterprise-auth-frontend",
        exportPath: "reset-password-page",
        exports: ["default"],
      },
      {
        relativePath: "app/api/embed/session/[token]/route.ts",
        packageName: "@radioso/enterprise-embed-widget",
        exportPath: "routes/embed-session",
        exports: ["OPTIONS", "POST"],
        runtime: "nodejs",
        dynamic: "force-dynamic",
      },
    ]);

    expect(files).toEqual([
      {
        relativePath: "app/reset-password/page.tsx",
        content: [
          "export { default } from '@radioso/enterprise-auth-frontend/reset-password-page'",
          "",
        ].join("\n"),
      },
      {
        relativePath: "app/api/embed/session/[token]/route.ts",
        content: [
          "export const runtime = 'nodejs'",
          "export const dynamic = 'force-dynamic'",
          "",
          "export {",
          "  OPTIONS,",
          "  POST,",
          "} from '@radioso/enterprise-embed-widget/routes/embed-session'",
          "",
        ].join("\n"),
      },
    ]);
  });

  it("writes and removes generated files under a supplied frontend root", async () => {
    tempRoot = await fs.mkdtemp(path.join(os.tmpdir(), "radioso-ee-routes-"));

    await enableEnterpriseFrontendRoutes({
      frontendRoot: tempRoot,
      routes: [{
        relativePath: "app/verify-email/page.tsx",
        packageName: "@radioso/enterprise-auth-frontend",
        exportPath: "verify-email-page",
        exports: ["default"],
      }],
    });

    const generated = await fs.readFile(path.join(tempRoot, "app/verify-email/page.tsx"), "utf8");
    expect(generated).toContain("Generated by scripts/sync-ee-frontend-routes.mjs");
    expect(generated).toContain("@radioso/enterprise-auth-frontend/verify-email-page");

    await disableEnterpriseFrontendRoutes({
      frontendRoot: tempRoot,
      routes: [{
        relativePath: "app/verify-email/page.tsx",
        packageName: "@radioso/enterprise-auth-frontend",
        exportPath: "verify-email-page",
        exports: ["default"],
      }],
    });

    await expect(fs.stat(path.join(tempRoot, "app/verify-email/page.tsx"))).rejects.toMatchObject({
      code: "ENOENT",
    });
  });

  it("removes stale generated route files even when routes are no longer in manifests", async () => {
    tempRoot = await fs.mkdtemp(path.join(os.tmpdir(), "radioso-ee-routes-"));
    const staleRoute = path.join(tempRoot, "app/old-enterprise-route/page.tsx");
    await fs.mkdir(path.dirname(staleRoute), { recursive: true });
    await fs.writeFile(
      staleRoute,
      [
        "// Generated by scripts/sync-ee-frontend-routes.mjs. Do not edit.",
        "export { default } from '@radioso/enterprise-auth-frontend/old-page'",
        "",
      ].join("\n"),
    );

    await disableEnterpriseFrontendRoutes({ frontendRoot: tempRoot, routes: [] });

    await expect(fs.stat(staleRoute)).rejects.toMatchObject({ code: "ENOENT" });
  });

  it("rejects route contributions that are missing from package exports", async () => {
    const packageExports = new Map([
      ["@radioso/enterprise-auth-frontend", new Set(["./verify-email-page"])],
    ]);

    const result = await validateFeatureManifests([
      {
        id: "auth-pages",
        docs: [],
        frontendRoutes: [{
          relativePath: "app/reset-password/page.tsx",
          packageName: "@radioso/enterprise-auth-frontend",
          exportPath: "reset-password-page",
          exports: ["default"],
        }],
      },
    ], {
      existingDocs: new Set(),
      packageExports,
    });

    expect(result.valid).toBe(false);
    expect(result.errors).toEqual([
      expect.stringContaining("references missing package export"),
    ]);
  });

  it("rejects route contributions missing packageName or exportPath", async () => {
    const result = await validateFeatureManifests([
      {
        id: "auth-pages",
        docs: [],
        frontendRoutes: [
          {
            relativePath: "app/reset-password/page.tsx",
            exportPath: "reset-password-page",
            exports: ["default"],
          },
          {
            relativePath: "app/verify-email/page.tsx",
            packageName: "@radioso/enterprise-auth-frontend",
            exports: ["default"],
          },
        ],
      },
    ], {
      existingDocs: new Set(),
      packageExports: new Map(),
    });

    expect(result.valid).toBe(false);
    expect(result.errors).toEqual([
      expect.stringContaining('route "app/reset-password/page.tsx" must declare packageName'),
      expect.stringContaining('route "app/verify-email/page.tsx" must declare exportPath'),
    ]);
  });

  it("keeps Docker frontend build inputs in sync with route manifest dependencies", async () => {
    const repoRoot = path.resolve(new URL("../../..", import.meta.url).pathname);
    const dockerfile = await fs.readFile(path.join(repoRoot, "infra/frontend.Dockerfile"), "utf8");

    expect(dockerfile).toContain("scripts/enterprise-feature-manifests.mjs");
    expect(dockerfile).toContain("ee/packages/auth-frontend/feature-manifest.mjs");
    expect(dockerfile).toContain("ee/packages/embed-widget/feature-manifest.mjs");
    expect(dockerfile).toContain("ee/packages/auth-frontend/package.json");
    expect(dockerfile).toContain("ee/packages/embed-widget/package.json");
  });
});
