import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";

const moduleUrl = new URL("../../../scripts/sync-ee-frontend-routes.mjs", import.meta.url);
const manifestModuleUrl = new URL("../../../scripts/enterprise-feature-manifests.mjs", import.meta.url);
const {
  buildAgentCreationActionsConfig,
  buildEnterpriseTailwindSources,
  buildGeneratedRouteFiles,
  buildOssTailwindSources,
  disableEnterpriseFrontendRoutes,
  enableEnterpriseFrontendRoutes,
} = await import(moduleUrl.href) as any;
const {
  validateFeatureManifests,
} = await import(manifestModuleUrl.href) as any;

let tempRoot: string | null = null;

afterEach(async () => {
  if (tempRoot) {
    await fs.rm(tempRoot, { recursive: true, force: true });
    tempRoot = null;
  }
});

describe("Enterprise frontend route sync", () => {
  it("builds generated route stubs from manifest route contributions", () => {
    const files = buildGeneratedRouteFiles([
      {
        relativePath: "app/sample/page.tsx",
        packageName: "@radioso/enterprise-sample-frontend",
        exportPath: "sample-page",
        exports: ["default"],
      },
      {
        relativePath: "app/api/agents/wizard/start/route.ts",
        packageName: "@radioso/enterprise-sample-frontend",
        exportPath: "routes/sample-start",
        exports: ["OPTIONS", "POST"],
        runtime: "nodejs",
        dynamic: "force-dynamic",
      },
    ]);

    expect(files).toEqual([
      {
        relativePath: "app/sample/page.tsx",
        content: [
          "export { default } from '@radioso/enterprise-sample-frontend/sample-page'",
          "",
        ].join("\n"),
      },
      {
        relativePath: "app/api/agents/wizard/start/route.ts",
        content: [
          "export const runtime = 'nodejs'",
          "export const dynamic = 'force-dynamic'",
          "",
          "export {",
          "  OPTIONS,",
          "  POST,",
          "} from '@radioso/enterprise-sample-frontend/routes/sample-start'",
          "",
        ].join("\n"),
      },
    ]);
  });

  it("builds agent creation action config from manifest contributions", () => {
    expect(buildAgentCreationActionsConfig([
      {
        id: "website",
        label: "Create from website",
        icon: "globe",
        hrefTemplate: "/account/{accountId}/w/{workspacePublicRouteKey}/agent-wizard",
      },
    ])).toEqual([
      "{",
      '  "actions": [',
      "    {",
      '      "id": "website",',
      '      "label": "Create from website",',
      '      "icon": "globe",',
      '      "hrefTemplate": "/account/{accountId}/w/{workspacePublicRouteKey}/agent-wizard"',
      "    }",
      "  ]",
      "}",
      "",
    ].join("\n"));
  });

  it("builds edition-specific Tailwind source files", () => {
    expect(buildEnterpriseTailwindSources()).toContain("../../ee/packages/*/src/**/*.{ts,tsx}");
    expect(buildOssTailwindSources()).toContain("No edition-specific Tailwind sources.");
  });

  it("keeps the checked-in frontend adapter independent of Enterprise package imports", async () => {
    const repoRoot = path.resolve(new URL("../../..", import.meta.url).pathname);
    const agentCreationContributions = await fs.readFile(
      path.join(repoRoot, "frontend/lib/agent-creation-contributions.tsx"),
      "utf8",
    );
    const tailwindSources = await fs.readFile(
      path.join(repoRoot, "frontend/app/edition-tailwind-sources.css"),
      "utf8",
    );

    expect(agentCreationContributions)
      .toContain("@radioso/agent-creation-contributions");
    expect(agentCreationContributions).not.toContain("@radioso/enterprise-sample-frontend");
    expect(agentCreationContributions).not.toContain("Generated by scripts/sync-ee-frontend-routes.mjs");
    expect(tailwindSources).toContain("No edition-specific Tailwind sources.");
  });

  it("writes and removes generated files under a supplied frontend root", async () => {
    tempRoot = await fs.mkdtemp(path.join(os.tmpdir(), "radioso-ee-routes-"));

    await enableEnterpriseFrontendRoutes({
      frontendRoot: tempRoot,
      routes: [{
        relativePath: "app/sample/page.tsx",
        packageName: "@radioso/enterprise-sample-frontend",
        exportPath: "sample-page",
        exports: ["default"],
      }],
      agentCreationActions: [{
        id: "website",
        label: "Create from website",
        icon: "globe",
        hrefTemplate: "/account/{accountId}/w/{workspacePublicRouteKey}/agent-wizard",
      }],
    });

    const generated = await fs.readFile(path.join(tempRoot, "app/sample/page.tsx"), "utf8");
    expect(generated).toContain("Generated by scripts/sync-ee-frontend-routes.mjs");
    expect(generated).toContain("@radioso/enterprise-sample-frontend/sample-page");
    const actionConfig = JSON.parse(await fs.readFile(path.join(tempRoot, "public/agent-creation-actions.json"), "utf8"));
    expect(actionConfig.actions).toEqual([{
      id: "website",
      label: "Create from website",
      icon: "globe",
      hrefTemplate: "/account/{accountId}/w/{workspacePublicRouteKey}/agent-wizard",
    }]);
    const tailwindSources = await fs.readFile(path.join(tempRoot, "app/edition-tailwind-sources.css"), "utf8");
    expect(tailwindSources).toContain("../../ee/packages/*/src/**/*.{ts,tsx}");

    await disableEnterpriseFrontendRoutes({
      frontendRoot: tempRoot,
      routes: [{
        relativePath: "app/sample/page.tsx",
        packageName: "@radioso/enterprise-sample-frontend",
        exportPath: "sample-page",
        exports: ["default"],
      }],
    });

    await expect(fs.stat(path.join(tempRoot, "app/sample/page.tsx"))).rejects.toMatchObject({
      code: "ENOENT",
    });
    await expect(fs.stat(path.join(tempRoot, "public/agent-creation-actions.json"))).rejects.toMatchObject({
      code: "ENOENT",
    });
    await expect(fs.readFile(path.join(tempRoot, "app/edition-tailwind-sources.css"), "utf8"))
      .resolves
      .toContain("No edition-specific Tailwind sources.");
  });

  it("removes stale generated route files even when routes are no longer in manifests", async () => {
    tempRoot = await fs.mkdtemp(path.join(os.tmpdir(), "radioso-ee-routes-"));
    const staleRoute = path.join(tempRoot, "app/old-enterprise-route/page.tsx");
    await fs.mkdir(path.dirname(staleRoute), { recursive: true });
    await fs.writeFile(
      staleRoute,
      [
        "// Generated by scripts/sync-ee-frontend-routes.mjs. Do not edit.",
        "export { default } from '@radioso/enterprise-sample-frontend/old-sample-page'",
        "",
      ].join("\n"),
    );

    await disableEnterpriseFrontendRoutes({ frontendRoot: tempRoot, routes: [] });

    await expect(fs.stat(staleRoute)).rejects.toMatchObject({ code: "ENOENT" });
  });

  it("rejects route contributions that are missing from package exports", async () => {
    const packageExports = new Map([
      ["@radioso/enterprise-sample-frontend", new Set(["./sample-page"])],
    ]);

    const result = await validateFeatureManifests([
      {
        id: "agent-wizard",
        docs: [],
        frontendRoutes: [{
          relativePath: "app/sample/settings/page.tsx",
          packageName: "@radioso/enterprise-sample-frontend",
          exportPath: "sample-settings-page",
          exports: ["default"],
        }],
      },
    ], {
      existingDocs: new Set(),
      packageExports,
    });

    expect(result.valid).toBe(false);
    expect(result.errors).toEqual([
      expect.stringContaining("references missing package export"),
    ]);
  });

  it("rejects route contributions missing packageName or exportPath", async () => {
    const result = await validateFeatureManifests([
      {
        id: "agent-wizard",
        docs: [],
        frontendRoutes: [
          {
            relativePath: "app/sample/page.tsx",
            exportPath: "sample-page",
            exports: ["default"],
          },
          {
            relativePath: "app/sample/settings/page.tsx",
            packageName: "@radioso/enterprise-sample-frontend",
            exports: ["default"],
          },
        ],
      },
    ], {
      existingDocs: new Set(),
      packageExports: new Map(),
    });

    expect(result.valid).toBe(false);
    expect(result.errors).toEqual([
      expect.stringContaining('route "app/sample/page.tsx" must declare packageName'),
      expect.stringContaining('route "app/sample/settings/page.tsx" must declare exportPath'),
    ]);
  });

  it("does not generate reset or verification pages from Enterprise manifests", async () => {
    const {
      collectFrontendRouteContributions,
      loadEnterpriseFeatureManifests,
    } = await import(manifestModuleUrl.href) as any;
    const frontendRouteContributions = collectFrontendRouteContributions(await loadEnterpriseFeatureManifests());

    expect(frontendRouteContributions.map((route: { relativePath: string }) => route.relativePath))
      .not
      .toEqual(expect.arrayContaining([
        "app/reset-password/page.tsx",
        "app/verify-email/page.tsx",
      ]));
  });

  it("keeps Docker frontend build inputs in sync with route manifest dependencies", async () => {
    const repoRoot = path.resolve(new URL("../../..", import.meta.url).pathname);
    const dockerfile = await fs.readFile(path.join(repoRoot, "infra/frontend.Dockerfile"), "utf8");

    expect(dockerfile).toContain("scripts/enterprise-feature-manifests.mjs");
    expect(dockerfile).toContain("ee/packages/auth-frontend/feature-manifest.mjs");
    expect(dockerfile).toContain("ee/packages/auth-frontend/package.json");
    expect(dockerfile).toContain("ee/readme.md");
    expect(dockerfile).toContain("COPY packages/ui/package.json ./packages/ui/package.json");
    expect(dockerfile).toContain("COPY packages/ui ./packages/ui");
    expect(dockerfile).toContain("COPY --chown=node:node --from=builder /app/packages/ui ./packages/ui");
  });
});
