'use client'

import { useCallback, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import { ArrowDown, ArrowRight, ArrowUp, Bot, CheckCircle2, CircleDashed, CornerUpRight, GitBranch, ListChecks, Plus, Settings2, Trash2, Wrench } from 'lucide-react'

import { RoutineInstructionEditor, type RoutineEditorVariable } from '@/components/dashboard/settings/routine-chip-editor'
import { findRoutineSkillDescriptor, RoutineSkillCatalogContext, RoutineSkillCatalogPopover } from '@/components/dashboard/settings/routine-skill-catalog-popover'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from '@/components/ui/dropdown-menu'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Switch } from '@/components/ui/switch'
import { Textarea } from '@/components/ui/textarea'
import type { RoutineDefinitionDraft, RoutineFieldGuardOp, RoutineGuardKind, RoutineReentryMode, RoutineSlotType, RoutineStepKind, RoutineTerminalKind } from '@/lib/api'
import { formatBindingLine, guardToSentence } from '@/lib/routine-document'
import {
  addBranch,
  addEnding,
  addSlot,
  addStep,
  changeBranchGuardKind,
  createEndingForBranch,
  moveStep,
  referenceEnding,
  removeBranch,
  removeSlot,
  removeStep,
  renameSlot,
  replaceInstruction,
  slotReferences,
  targetBranchAtStep,
  updateActivation,
  updateApproval,
  updateBindings,
  updateBranchGuard,
  updateEnding,
  updateSlot,
  updateStep,
} from '@/lib/routine-document-edits'
import { draftFromBlockDoc, routineToBlockDoc, slugifyVariableKey, type ProseParagraph, type ProseSegment, type RoutineBlockBranch, type RoutineBlockDoc, type RoutineBlockEnding, type RoutineBlockGuard, type RoutineBlockInstructionSegment, type RoutineBlockStep, type RoutineInputBinding } from '@/lib/routine-prose'

const slotTypes: RoutineSlotType[] = ['text', 'number', 'boolean', 'email', 'date']
const guardKinds: RoutineGuardKind[] = ['field', 'slot_filled', 'outcome', 'counter', 'default']
const branchEnding = (branch: RoutineBlockBranch) => branch.target.kind === 'ending' ? branch.target.ending : undefined

function Instruction({ segments }: { segments: RoutineBlockInstructionSegment[] }) {
  return <p className="leading-7 text-foreground">{segments.map((segment, index) => segment.kind === 'text' ? segment.text : <span key={`${segment.key}-${index}`} className="mx-0.5 inline-flex select-none items-center rounded-md border border-emerald-300 bg-emerald-100 px-1.5 py-0 align-baseline text-xs font-medium text-emerald-900">{segment.key}</span>)}</p>
}

const instructionParagraph = (segments: RoutineBlockInstructionSegment[]): ProseParagraph[] => [{
  segments: segments.map((segment): ProseSegment => segment.kind === 'text'
    ? segment
    : { kind: 'chip', chipKind: 'variable', refId: segment.key, label: segment.key }),
}]

const segmentsFromParagraph = (segments: ProseSegment[]): RoutineBlockInstructionSegment[] => segments.map((segment) => segment.kind === 'text'
  ? segment
  : { kind: 'slotReference', key: segment.refId, source: `{{slot.${segment.refId}}}` })

const endingList = (doc: RoutineBlockDoc): RoutineBlockEnding[] => {
  const endings = new Map<string, RoutineBlockEnding>()
  for (const ending of doc.unreferencedEndings) endings.set(ending.stableStepId, ending)
  for (const branch of doc.steps.flatMap((step) => step.branches)) {
    if (branch.target.kind === 'ending' && branch.target.ending) endings.set(branch.target.ending.stableStepId, branch.target.ending)
  }
  return [...endings.values()]
}

function RoutineDocumentReader({ doc }: { doc: RoutineBlockDoc }) {
  const catalog = useContext(RoutineSkillCatalogContext)
  const slotNames = new Map(doc.information.map((slot) => [slot.key, slot.key]))
  return (
    <article className="space-y-6 rounded-lg border border-border bg-background p-5" aria-label="Routine document">
      <header className="border-b border-border pb-4"><h2 className="text-xl font-semibold tracking-tight text-foreground">{doc.name || 'Untitled routine'}</h2><p className="mt-1 text-sm text-muted-foreground">Starts when {doc.activation.triggerDescription || 'an activation trigger is met'}.</p></header>
      <section aria-labelledby="routine-document-information"><h3 id="routine-document-information" className="text-sm font-semibold text-foreground">Information</h3>{doc.information.length === 0 ? <p className="mt-2 text-sm text-muted-foreground">No information is collected.</p> : <ul className="mt-2 divide-y divide-border rounded-md border border-border">{doc.information.map((slot) => <li key={slot.stableSlotId} className="flex flex-wrap items-baseline gap-x-2 gap-y-1 px-3 py-2 text-sm"><span className="font-medium text-foreground">{slot.key}</span><Badge variant="outline" className="font-normal">{slot.type}</Badge><span className={slot.required ? 'text-amber-700 dark:text-amber-300' : 'text-muted-foreground'}>{slot.required ? 'required' : 'optional'}</span>{slot.description ? <span className="basis-full text-muted-foreground">{slot.description}</span> : null}</li>)}</ul>}</section>
      <section aria-labelledby="routine-document-steps"><h3 id="routine-document-steps" className="text-sm font-semibold text-foreground">Steps</h3><ol className="mt-3 space-y-3">{doc.steps.map((step, stepIndex) => {
        const ref = step.kind === 'tool' ? step.toolRef : step.kind === 'action' ? step.actionType : null
        const descriptor = ref ? findRoutineSkillDescriptor(catalog.skills, ref, ref) : undefined
        const label = step.kind === 'approval' ? 'Approval' : descriptor?.displayName ?? ref ?? 'Chat'
        return <li key={step.stableStepId} className="rounded-lg border border-border p-4"><div className="flex items-center gap-2 text-sm font-medium text-foreground"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-muted text-xs">{stepIndex + 1}</span>{step.kind === 'approval' ? <ListChecks className="h-4 w-4" /> : step.kind === 'tool' || step.kind === 'action' ? <Wrench className="h-4 w-4" /> : <Bot className="h-4 w-4" />}<span>{label}</span></div><div className="mt-3"><Instruction segments={step.instruction} /></div>{step.kind === 'tool' || step.kind === 'action' ? <p className="mt-3 flex items-center gap-1 text-xs text-muted-foreground"><ArrowRight className="h-3.5 w-3.5" />{formatBindingLine(step.inputBindings, step.outputAssignments) ?? 'uses nothing → sets nothing'}</p> : null}{step.kind === 'approval' ? <div className="mt-3 rounded-md bg-violet-50 p-3 text-sm text-violet-950 dark:bg-violet-500/10 dark:text-violet-100"><p className="font-medium">A person chooses:</p><ul className="mt-2 space-y-1">{(step.options ?? []).map((option) => <li key={option.id}>{option.label}{option.description ? ` — ${option.description}` : ''}</li>)}</ul></div> : null}{step.branches.length > 0 ? <ul className="mt-4 space-y-2 border-l border-border pl-3">{step.branches.map((branch, index) => { const branchIsAi = branch.guard.provenance === 'judgment'; return <li key={`${step.stableStepId}-${index}`} className="rounded-md bg-muted/50 p-2 text-sm"><div className="flex flex-wrap items-center gap-2"><Badge variant="outline" className={branchIsAi ? 'border-violet-300 bg-violet-100 text-violet-900 dark:border-violet-500/70 dark:bg-violet-500/15 dark:text-violet-100' : 'border-indigo-300 bg-indigo-100 text-indigo-900 dark:border-indigo-500/70 dark:bg-indigo-500/15 dark:text-indigo-100'}>{branchIsAi ? 'AI decides' : 'Rule'}</Badge><span>{guardToSentence(branch.guard, slotNames)}</span><GitBranch className="h-3.5 w-3.5 text-muted-foreground" />{branch.target.kind === 'step' ? <span>continue to {branch.target.stableStepId}</span> : branch.target.ending ? <span className="inline-flex items-center gap-1">{branch.target.ending.kind === 'complete' ? <CheckCircle2 className="h-3.5 w-3.5" /> : <CornerUpRight className="h-3.5 w-3.5" />}{branch.target.ending.kind === 'complete' ? 'finish' : 'hand off'}{branch.target.ending.instruction ? `: ${branch.target.ending.instruction}` : ''}</span> : <span className="inline-flex items-center gap-1 text-muted-foreground"><CircleDashed className="h-3.5 w-3.5" />see {branch.target.terminalId} ending</span>}</div></li> })}</ul> : null}</li>
      })}</ol></section>
      {doc.unreferencedEndings.length > 0 ? <section aria-labelledby="routine-document-endings"><h3 id="routine-document-endings" className="text-sm font-semibold text-foreground">Endings</h3><ul className="mt-2 space-y-2">{doc.unreferencedEndings.map((ending) => <li key={ending.stableStepId} className="flex items-center gap-2 rounded-md bg-muted/50 p-3 text-sm">{ending.kind === 'complete' ? <CheckCircle2 className="h-4 w-4" /> : <CornerUpRight className="h-4 w-4" />}<span>{ending.kind === 'complete' ? 'Finish' : 'Hand off'}{ending.instruction ? `: ${ending.instruction}` : ''}</span></li>)}</ul></section> : null}
    </article>
  )
}

function GuardEditor({ branch, slots, onChange }: { branch: RoutineBlockBranch; slots: RoutineBlockDoc['information']; onChange: (patch: Partial<RoutineBlockGuard>) => void }) {
  const guard = branch.guard
  if (guard.kind === 'llm') return <Input aria-label="AI condition" value={guard.guardText ?? ''} onChange={(event) => onChange({ guardText: event.target.value })} placeholder="Describe what the AI should decide" />
  if (guard.kind === 'slot_filled') return <div className="flex flex-wrap gap-2">{slots.map((slot) => <label key={slot.stableSlotId} className="flex items-center gap-1 text-xs"><input type="checkbox" checked={guard.slotKeys.includes(slot.key)} onChange={(event) => onChange({ slotKeys: event.target.checked ? [...guard.slotKeys, slot.key] : guard.slotKeys.filter((key) => key !== slot.key) })} />{slot.key}</label>)}</div>
  if (guard.kind === 'field') return <div className="grid gap-2 sm:grid-cols-3"><select aria-label="Rule variable" value={guard.fieldRef ?? ''} onChange={(event) => onChange({ fieldRef: event.target.value })} className="h-9 rounded-md border border-input bg-transparent px-2 text-sm"><option value="">Variable…</option>{slots.map((slot) => <option key={slot.key} value={slot.key}>{slot.key}</option>)}</select><select aria-label="Rule operator" value={guard.fieldOp ?? 'equals'} onChange={(event) => onChange({ fieldOp: event.target.value as RoutineFieldGuardOp })} className="h-9 rounded-md border border-input bg-transparent px-2 text-sm">{['equals', 'not_equals', 'in', 'is_present', 'is_absent', 'is_true', 'is_false', 'gt', 'gte', 'lt', 'lte', 'older_than', 'within'].map((value) => <option key={value} value={value}>{value.replaceAll('_', ' ')}</option>)}</select><Input aria-label="Rule value" value={String(guard.fieldValue ?? '')} onChange={(event) => onChange({ fieldValue: event.target.value })} placeholder="Value" /></div>
  if (guard.kind === 'outcome') return <Input aria-label="Outcome status" value={guard.outcomeStatus ?? ''} onChange={(event) => onChange({ outcomeStatus: event.target.value })} placeholder="succeeded" />
  if (guard.kind === 'counter') return <Input aria-label="Counter limit" type="number" min={1} value={guard.counterLimit ?? ''} onChange={(event) => onChange({ counterLimit: Number(event.target.value) || null })} />
  return <span className="text-xs text-muted-foreground">Otherwise, continue.</span>
}

function DocumentEditor({ initialDoc, onDraftChange }: { initialDoc: RoutineBlockDoc; onDraftChange: (draft: RoutineDefinitionDraft) => void }) {
  const catalog = useContext(RoutineSkillCatalogContext)
  const [doc, setDoc] = useState(initialDoc)
  const [slotRemovalError, setSlotRemovalError] = useState<string | null>(null)
  const sourceSignature = JSON.stringify(initialDoc)
  const sourceRef = useRef(sourceSignature)
  useEffect(() => { if (sourceRef.current !== sourceSignature) { sourceRef.current = sourceSignature; setDoc(initialDoc) } }, [initialDoc, sourceSignature])
  const apply = useCallback((edit: (current: RoutineBlockDoc) => RoutineBlockDoc) => {
    setDoc((current) => { const next = edit(current); onDraftChange(draftFromBlockDoc(next)); return next })
  }, [onDraftChange])
  const variables = useMemo(() => doc.information.map((slot) => ({ id: slot.key, name: slot.key, type: slot.type, required: slot.required, mutable: slot.mutable ?? false })), [doc.information])
  const endings = useMemo(() => endingList(doc), [doc])
  const addVariable = (variable: RoutineEditorVariable) => apply((current) => current.information.some((slot) => slot.key === variable.id) ? current : ({ ...current, information: [...current.information, { stableSlotId: variable.id, key: variable.id, type: 'text', required: true, description: null, mutable: false }] }))
  const targetOptions = (stepId: string) => <><option value="">Choose target…</option>{doc.steps.filter((step) => step.stableStepId !== stepId).map((step) => <option key={step.stableStepId} value={`step:${step.stableStepId}`}>Step: {step.instruction.map((segment) => segment.kind === 'text' ? segment.text : segment.key).join('').trim() || step.stableStepId}</option>)}{endings.map((ending) => <option key={ending.stableStepId} value={`ending:${ending.stableStepId}`}>{ending.kind === 'complete' ? 'Finish' : 'Hand off'}: {ending.instruction || ending.stableStepId}</option>)}</>
  return <article className="space-y-6 rounded-lg border border-border bg-background p-5" aria-label="Routine document editor">
    <header className="space-y-3 border-b border-border pb-4"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-semibold tracking-tight text-foreground">{doc.name || 'Untitled routine'}</h2><p className="text-xs text-muted-foreground">Edit structure with the controls below; instructions accept only text and @ variables.</p></div><DropdownMenu><DropdownMenuTrigger asChild><Button type="button" variant="outline" size="sm"><Settings2 className="mr-1 h-4 w-4" />Activation</Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-64 p-3"><DropdownMenuLabel>Activation settings</DropdownMenuLabel><Label className="mt-2 block text-xs">Reentry</Label><select value={doc.activation.reentryMode ?? 'once_per_conversation'} onChange={(event) => apply((current) => updateActivation(current, { reentryMode: event.target.value as RoutineReentryMode }))} className="mt-1 h-9 w-full rounded-md border border-input bg-transparent px-2 text-sm"><option value="once_per_conversation">Once per conversation</option><option value="always">Every time it matches</option><option value="semantic">Let the assistant decide</option></select><Label className="mt-3 block text-xs">Priority</Label><Input type="number" value={doc.activation.priority} onChange={(event) => apply((current) => updateActivation(current, { priority: Number(event.target.value) || 0 }))} /></DropdownMenuContent></DropdownMenu></div><Textarea aria-label="Activation trigger" value={doc.activation.triggerDescription} onChange={(event) => apply((current) => updateActivation(current, { triggerDescription: event.target.value }))} placeholder="Starts when…" rows={2} /></header>

    <section><div className="flex items-center justify-between"><h3 className="text-sm font-semibold">Information</h3><Button type="button" size="sm" variant="outline" onClick={() => apply(addSlot)}><Plus className="mr-1 h-4 w-4" />Slot</Button></div>{slotRemovalError ? <p role="alert" className="mt-2 text-xs text-destructive">{slotRemovalError}</p> : null}<div className="mt-3 space-y-2">{doc.information.map((slot) => <div key={slot.stableSlotId} className="grid gap-2 rounded-md border border-border p-3 sm:grid-cols-[130px_120px_1fr_auto]"><Input aria-label={`Slot ${slot.key} name`} value={slot.key} onChange={(event) => apply((current) => renameSlot(current, slot.stableSlotId, event.target.value))} /><select aria-label={`Slot ${slot.key} type`} value={slot.type} onChange={(event) => apply((current) => updateSlot(current, slot.stableSlotId, { type: event.target.value as RoutineSlotType }))} className="h-9 rounded-md border border-input bg-transparent px-2 text-sm">{slotTypes.map((type) => <option key={type}>{type}</option>)}</select><Input aria-label={`Slot ${slot.key} description`} value={slot.description ?? ''} onChange={(event) => apply((current) => updateSlot(current, slot.stableSlotId, { description: event.target.value || null }))} placeholder="Description" /><div className="flex items-center gap-2"><Label className="text-xs">Required</Label><Switch checked={slot.required} onCheckedChange={(checked) => apply((current) => updateSlot(current, slot.stableSlotId, { required: checked }))} /><Button type="button" size="sm" variant="ghost" aria-label={`Remove slot ${slot.key}`} onClick={() => { const refs = slotReferences(doc, slot.key); if (refs.length) { setSlotRemovalError(`Can't remove ${slot.key}; it is referenced by ${refs.join(', ')}. Remove those references first.`); return } setSlotRemovalError(null); apply((current) => removeSlot(current, slot.stableSlotId)) }}><Trash2 className="h-4 w-4" /></Button></div></div>)}</div></section>

    <section><div className="flex items-center justify-between"><h3 className="text-sm font-semibold">Steps</h3><DropdownMenu><DropdownMenuTrigger asChild><Button type="button" size="sm"><Plus className="mr-1 h-4 w-4" />Step</Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={() => apply((current) => addStep(current, 'chat'))}>Chat</DropdownMenuItem><DropdownMenuSeparator /><DropdownMenuLabel>Use a skill</DropdownMenuLabel>{catalog.skills.map((skill) => <DropdownMenuItem key={skill.skillName} onSelect={() => apply((current) => { const next = addStep(current, 'tool'); return updateStep(next, next.steps.at(-1)!.stableStepId, { toolRef: skill.skillName }) })}>{skill.displayName}</DropdownMenuItem>)}<DropdownMenuSeparator /><DropdownMenuItem onSelect={() => apply((current) => addStep(current, 'approval'))}>Approval</DropdownMenuItem><DropdownMenuLabel>Action</DropdownMenuLabel>{catalog.skills.map((skill) => <DropdownMenuItem key={`action-${skill.skillName}`} onSelect={() => apply((current) => { const next = addStep(current, 'action'); return updateStep(next, next.steps.at(-1)!.stableStepId, { actionType: skill.skillName }) })}>{skill.displayName}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu></div><ol className="mt-3 space-y-3">{doc.steps.map((step, stepIndex) => <StepEditor key={step.stableStepId} step={step} stepIndex={stepIndex} doc={doc} variables={variables} targetOptions={targetOptions} apply={apply} addVariable={addVariable} />)}</ol></section>

    <section><div className="flex items-center justify-between"><h3 className="text-sm font-semibold">Endings</h3><div className="flex gap-2"><Button type="button" size="sm" variant="outline" onClick={() => apply((current) => addEnding(current, 'complete'))}>Finish</Button><Button type="button" size="sm" variant="outline" onClick={() => apply((current) => addEnding(current, 'handoff'))}>Hand off</Button></div></div><div className="mt-3 space-y-2">{endings.map((ending) => <div key={ending.stableStepId} className="flex gap-2 rounded-md border border-border p-2"><Badge variant="outline">{ending.kind === 'complete' ? 'Finish' : 'Hand off'}</Badge><Input aria-label={`${ending.stableStepId} message`} value={ending.instruction ?? ''} onChange={(event) => apply((current) => updateEnding(current, ending.stableStepId, { instruction: event.target.value }))} placeholder="Message (optional)" /></div>)}</div></section>
  </article>
}

function StepEditor({ step, stepIndex, doc, variables, targetOptions, apply, addVariable }: { step: RoutineBlockStep; stepIndex: number; doc: RoutineBlockDoc; variables: Array<{ id: string; name: string; type: RoutineSlotType; required: boolean; mutable: boolean }>; targetOptions: (stepId: string) => ReactNode; apply: (edit: (current: RoutineBlockDoc) => RoutineBlockDoc) => void; addVariable: (variable: RoutineEditorVariable) => void }) {
  const catalog = useContext(RoutineSkillCatalogContext)
  const updateBindingState = (state: { inputBindings?: Record<string, RoutineInputBinding>; outputAssignments?: Record<string, string>; mode?: 'typed' | 'untyped' }) => apply((current) => updateBindings(current, step.stableStepId, state))
  return <li className="space-y-3 rounded-lg border border-border p-4"><div className="flex flex-wrap items-center gap-2"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-muted text-xs">{stepIndex + 1}</span><Badge variant="outline">{step.kind === 'approval' ? 'Approval' : step.kind}</Badge>{step.kind === 'tool' || step.kind === 'action' ? <select aria-label={`${step.stableStepId} catalog item`} value={step.kind === 'tool' ? step.toolRef ?? '' : step.actionType ?? ''} onChange={(event) => apply((current) => updateStep(current, step.stableStepId, step.kind === 'tool' ? { toolRef: event.target.value } : { actionType: event.target.value }))} className="h-9 min-w-44 rounded-md border border-input bg-transparent px-2 text-sm"><option value="">Choose from catalog…</option>{catalog.skills.map((skill) => <option key={skill.skillName} value={skill.skillName}>{skill.displayName}</option>)}</select> : null}<span className="flex-1" /><Button type="button" size="icon" variant="ghost" disabled={stepIndex === 0} aria-label="Move step up" onClick={() => apply((current) => moveStep(current, step.stableStepId, -1))}><ArrowUp className="h-4 w-4" /></Button><Button type="button" size="icon" variant="ghost" disabled={stepIndex === doc.steps.length - 1} aria-label="Move step down" onClick={() => apply((current) => moveStep(current, step.stableStepId, 1))}><ArrowDown className="h-4 w-4" /></Button><Button type="button" size="icon" variant="ghost" aria-label="Remove step" onClick={() => apply((current) => removeStep(current, step.stableStepId))}><Trash2 className="h-4 w-4" /></Button></div>
    <RoutineInstructionEditor initialContent={instructionParagraph(step.instruction)} variables={variables} onCreateVariable={addVariable} onChange={(segments) => apply((current) => replaceInstruction(current, step.stableStepId, segmentsFromParagraph(segments)))} />
    {step.kind === 'tool' || step.kind === 'action' ? <div className="space-y-2 rounded-md bg-muted/40 p-2 text-xs"><div className="flex flex-wrap items-center gap-2"><span>{formatBindingLine(step.inputBindings, step.outputAssignments) ?? 'uses nothing → sets nothing'}</span><RoutineSkillCatalogPopover skillName={step.kind === 'tool' ? step.toolRef ?? '' : step.actionType ?? ''} label="Edit bindings" bindingState={{ inputBindings: step.inputBindings, outputAssignments: step.outputAssignments, mode: step.mode }} availableVariables={variables.map((variable) => variable.id)} onBindingStateChange={updateBindingState}><Button type="button" size="sm" variant="outline">Edit inputs</Button></RoutineSkillCatalogPopover></div><BindingAssignments assignments={step.outputAssignments ?? {}} onChange={(outputAssignments) => updateBindingState({ inputBindings: step.inputBindings, outputAssignments, mode: step.mode })} onCreateVariable={addVariable} /></div> : null}
    {step.kind === 'approval' ? <ApprovalEditor step={step} apply={apply} /> : null}
    {step.kind !== 'approval' ? <div className="space-y-2"><div className="flex items-center justify-between"><p className="text-xs font-medium uppercase text-muted-foreground">Branches</p><Button type="button" size="sm" variant="outline" onClick={() => apply((current) => addBranch(current, step.stableStepId))}><Plus className="mr-1 h-3.5 w-3.5" />Condition</Button></div>{step.branches.map((branch, branchIndex) => <div key={branchIndex} className="space-y-2 rounded-md border border-border p-2"><div className="grid gap-2 sm:grid-cols-[130px_150px_1fr_auto]"><select aria-label="Decision kind" value={branch.guard.kind === 'llm' ? 'llm' : 'rule'} onChange={(event) => apply((current) => changeBranchGuardKind(current, step.stableStepId, branchIndex, event.target.value === 'llm' ? 'llm' : 'field'))} className="h-9 rounded-md border border-input bg-transparent px-2 text-sm"><option value="rule">Rule</option><option value="llm">AI decides</option></select>{branch.guard.kind !== 'llm' ? <select aria-label="Rule kind" value={branch.guard.kind} onChange={(event) => apply((current) => changeBranchGuardKind(current, step.stableStepId, branchIndex, event.target.value as RoutineGuardKind))} className="h-9 rounded-md border border-input bg-transparent px-2 text-sm">{guardKinds.map((kind) => <option key={kind} value={kind}>{kind.replaceAll('_', ' ')}</option>)}</select> : <span />}
        <select aria-label="Branch target" value={branch.target.kind === 'step' ? `step:${branch.target.stableStepId}` : `ending:${branch.target.terminalId}`} onChange={(event) => { const [kind, id] = event.target.value.split(':'); apply((current) => kind === 'step' ? targetBranchAtStep(current, step.stableStepId, branchIndex, id!) : referenceEnding(current, step.stableStepId, branchIndex, id!)) }} className="h-9 rounded-md border border-input bg-transparent px-2 text-sm">{targetOptions(step.stableStepId)}</select><Button type="button" variant="ghost" size="sm" aria-label="Remove condition" onClick={() => apply((current) => removeBranch(current, step.stableStepId, branchIndex))}><Trash2 className="h-4 w-4" /></Button></div><GuardEditor branch={branch} slots={doc.information} onChange={(patch) => apply((current) => updateBranchGuard(current, step.stableStepId, branchIndex, patch))} />{branch.target.kind === 'ending' ? <div className="flex flex-wrap gap-2"><Button type="button" size="sm" variant="outline" onClick={() => apply((current) => createEndingForBranch(current, step.stableStepId, branchIndex, 'complete'))}>New finish</Button><Button type="button" size="sm" variant="outline" onClick={() => apply((current) => createEndingForBranch(current, step.stableStepId, branchIndex, 'handoff'))}>New hand-off</Button>{branchEnding(branch) ? <Input aria-label="Ending message" value={branchEnding(branch)?.instruction ?? ''} onChange={(event) => { const ending = branchEnding(branch); if (ending) apply((current) => updateEnding(current, ending.stableStepId, { instruction: event.target.value })) }} placeholder="Ending message" /> : null}</div> : null}</div>)}</div> : null}
  </li>
}

function BindingAssignments({ assignments, onChange, onCreateVariable }: { assignments: Record<string, string>; onChange: (assignments: Record<string, string>) => void; onCreateVariable: (variable: RoutineEditorVariable) => void }) {
  const entries = Object.entries(assignments)
  const update = (index: number, key: string, value: string) => {
    const next = Object.fromEntries(entries.filter((_, candidate) => candidate !== index))
    const normalized = value.trim() ? slugifyVariableKey(value) : ''
    if (key.trim()) next[key.trim()] = normalized
    onChange(next)
    if (value.trim()) onCreateVariable({ id: normalized, name: value.trim() })
  }
  return <div className="space-y-1"><div className="flex items-center justify-between"><span className="font-medium">Sets</span><Button type="button" size="sm" variant="ghost" onClick={() => onChange({ ...assignments, [`output_${entries.length + 1}`]: '' })}><Plus className="mr-1 h-3.5 w-3.5" />Output</Button></div>{entries.map(([output, variable], index) => <div key={`${output}-${index}`} className="grid grid-cols-[1fr_1fr_auto] gap-2"><Input aria-label={`Output ${index + 1} name`} value={output} onChange={(event) => update(index, event.target.value, variable)} placeholder="Output" /><Input aria-label={`Output ${index + 1} variable`} value={variable} onChange={(event) => update(index, output, event.target.value)} placeholder="Existing or new variable" /><Button type="button" size="sm" variant="ghost" aria-label={`Remove output ${index + 1}`} onClick={() => onChange(Object.fromEntries(entries.filter((_, candidate) => candidate !== index)))}><Trash2 className="h-4 w-4" /></Button></div>)}</div>
}

function ApprovalEditor({ step, apply }: { step: RoutineBlockStep; apply: (edit: (current: RoutineBlockDoc) => RoutineBlockDoc) => void }) {
  const options = step.options ?? []
  return <div className="space-y-2 rounded-md bg-violet-500/5 p-3"><Label>Question</Label><Textarea aria-label="Approval question" value={step.instruction.map((segment) => segment.kind === 'text' ? segment.text : `{{slot.${segment.key}}}`).join('')} onChange={(event) => apply((current) => updateApproval(current, step.stableStepId, { instruction: [{ kind: 'text', text: event.target.value }] }))} rows={2} /><Label>Capture key</Label><Input aria-label="Approval capture key" value={step.captureKey ?? ''} onChange={(event) => apply((current) => updateApproval(current, step.stableStepId, { captureKey: slugifyVariableKey(event.target.value) }))} />{options.map((option, index) => <div key={option.id} className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><Input aria-label={`Approval option ${index + 1} label`} value={option.label} onChange={(event) => apply((current) => updateApproval(current, step.stableStepId, { options: options.map((item, itemIndex) => itemIndex === index ? { ...item, label: event.target.value } : item) }))} placeholder="Label" /><Input aria-label={`Approval option ${index + 1} description`} value={option.description ?? ''} onChange={(event) => apply((current) => updateApproval(current, step.stableStepId, { options: options.map((item, itemIndex) => itemIndex === index ? { ...item, description: event.target.value } : item) }))} placeholder="Description" /><Button type="button" size="sm" variant="ghost" disabled={options.length <= 2} onClick={() => apply((current) => updateApproval(current, step.stableStepId, { options: options.filter((_, itemIndex) => itemIndex !== index) }))}><Trash2 className="h-4 w-4" /></Button></div>)}<Button type="button" size="sm" variant="outline" onClick={() => apply((current) => updateApproval(current, step.stableStepId, { options: [...options, { id: `option_${options.length + 1}`, label: '', description: '' }] }))}><Plus className="mr-1 h-3.5 w-3.5" />Option</Button><p className="text-xs text-muted-foreground">At least two options are required.</p></div>
}

export function RoutineDocumentTab({ draft, isReadOnly = true, onDraftChange }: { draft: RoutineDefinitionDraft; isReadOnly?: boolean; onDraftChange?: (draft: RoutineDefinitionDraft) => void }) {
  const result = useMemo(() => routineToBlockDoc(draft), [draft])
  if (!result.ok) return <div className="rounded-lg border border-dashed border-border p-4" role="status"><p className="font-medium text-foreground">This routine can’t be displayed as a document yet.</p><p className="mt-1 text-sm text-muted-foreground">Use the <strong>Form</strong> tab to resolve the following:</p><ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-muted-foreground">{result.diagnostics.map((diagnostic) => <li key={`${diagnostic.code}-${diagnostic.message}`}>{diagnostic.message}</li>)}</ul></div>
  return isReadOnly || !onDraftChange ? <RoutineDocumentReader doc={result.doc} /> : <DocumentEditor initialDoc={result.doc} onDraftChange={onDraftChange} />
}
