/**
 * `@radioso/app-contract` is the provider-neutral vocabulary for Hosted Apps:
 * what a manifest may declare, what an invocation looks like on the wire, and
 * what a host admits. It is schemas and pure functions only, so the same rules
 * hold in the API process, in a worker, in an App, and in a conformance run.
 */
export {
  appIdSchema,
  assetIdSchema,
  collectionIdSchema,
  connectionSlotIdSchema,
  contributionIdSchema,
  descriptionSchema,
  destinationIdSchema,
  digestSchema,
  displayNameSchema,
  fieldKeySchema,
  fixtureIdSchema,
  httpHeaderNameSchema,
  indexIdSchema,
  indexedFieldKeySchema,
  schemaVersionSchema,
  semanticVersionRangeSchema,
  semanticVersionSchema,
  timestampSchema,
  type AppId,
  type CollectionId,
  type ContributionId,
  type ConnectionSlotId,
  type DestinationId,
  type Digest,
  type FieldKey,
  type IndexedFieldKey,
  type SemanticVersion,
  type SemanticVersionRange,
} from "./identifiers.js";

export {
  MAX_BASE64_DECODED_BYTES,
  MAX_HEADER_ENTRIES,
  MAX_JSON_ARRAY_ITEMS,
  MAX_JSON_DEPTH,
  MAX_JSON_OBJECT_KEYS,
  MAX_JSON_SERIALIZED_BYTES,
  MAX_JSON_STRING_LENGTH,
  base64BodySchema,
  base64DecodedByteLength,
  boundedJsonRecordSchema,
  boundedJsonValueSchema,
  type BoundedJsonRecord,
  type BoundedJsonValue,
} from "./bounds.js";

export {
  MAX_CONFIGURATION_ENTRIES,
  MAX_CONFIGURATION_VALUE_LENGTH,
  appConfigurationSchema,
  configurationFieldSchema,
  configurationFieldTypeSchema,
  configurationFieldTypes,
  configurationSelectOptionSchema,
  configurationValueSchema,
  configurationValuesSchema,
  type AppConfiguration,
  type ConfigurationField,
  type ConfigurationFieldType,
  type ConfigurationValue,
  type ConfigurationValues,
} from "./configuration.js";

export {
  appConnectionsSchema,
  connectionSecretFieldSchema,
  connectionSlotKindSchema,
  connectionSlotKinds,
  connectionSlotSchema,
  generatedSecretSlotSchema,
  oauth2SlotSchema,
  secretFieldsSlotSchema,
  type AppConnections,
  type ConnectionSlot,
  type ConnectionSlotKind,
} from "./connections.js";

export {
  destinationCredentialApplicationSchema,
  destinationCredentialsSchema,
  destinationDataClassSchema,
  destinationDataClasses,
  destinationHostSchema,
  destinationProtocolSchema,
  destinationProtocols,
  destinationSchema,
  type Destination,
  type DestinationCredentialApplication,
  type DestinationCredentials,
  type DestinationDataClass,
  type DestinationHost,
  type DestinationProtocol,
} from "./destinations.js";

export {
  isScalarStorageFieldType,
  scalarStorageFieldTypes,
  storageCollectionSchema,
  storageDeleteRequestSchema,
  storageFieldTypeSchema,
  storageFieldTypes,
  storageGetRequestSchema,
  storageIndexSchema,
  storageKeySchema,
  storageOperationSchema,
  storageOperations,
  storagePutRequestSchema,
  storageQueryRequestSchema,
  storageQueryResultSchema,
  storageRecordFieldSchema,
  storageRecordSchema,
  storageRetentionSchema,
  storageRecordValueSchema,
  storageScalarValueSchema,
  storageVersionSchema,
  type StorageCollection,
  type StorageDeleteRequest,
  type StorageFieldType,
  type StorageGetRequest,
  type StorageOperation,
  type StoragePutRequest,
  type StorageQueryRequest,
  type StorageQueryResult,
  type StorageRecord,
} from "./storage.js";

export {
  MAX_INDEXED_FIELDS,
  MAX_SCHEDULE_INTERVAL_SECONDS,
  contributionKindSchema,
  contributionKinds,
  contributionSchema,
  documentSourceContributionSchema,
  executionClassForContributionKind,
  executionClassSchema,
  executionClasses,
  externalWebhookHandlerContributionSchema,
  hostPermissionSchema,
  hostPermissions,
  indexedFieldsPolicySchema,
  releaseAContributionKinds,
  reservedContributionKinds,
  scheduleSchema,
  scheduledTaskContributionSchema,
  type ConfigurationSchedule,
  type Contribution,
  type ContributionKind,
  type DocumentSourceContribution,
  type ExecutionClass,
  type ExternalWebhookHandlerContribution,
  type HostPermission,
  type IndexedFieldsPolicy,
  type ScheduledTaskContribution,
} from "./contributions.js";

export {
  companionAssetSchema,
  setupGuideSchema,
  setupGuideSectionSchema,
  type CompanionAsset,
  type SetupGuide,
} from "./setup.js";

export {
  MANIFEST_SCHEMA_VERSION,
  appArtifactSchema,
  appManifestSchema,
  artifactMediaTypeSchema,
  artifactMediaTypes,
  conformanceFixtureSchema,
  resourceProfileSchema,
  type AppArtifact,
  type AppManifest,
  type ConformanceFixture,
  type ResourceProfile,
} from "./manifest.js";

export {
  MAX_DOCUMENT_METADATA_KEYS,
  MAX_EGRESS_QUERY_BYTES,
  MAX_EGRESS_QUERY_ENTRIES,
  MAX_ERROR_MESSAGE_LENGTH,
  RUNTIME_PROTOCOL_VERSION,
  appErrorCodeSchema,
  appErrorCodes,
  appErrorSchema,
  backfillInvocationInputSchema,
  capabilitySessionSchema,
  documentContentFormatSchema,
  documentDeleteResultSchema,
  documentIngestInputSchema,
  documentIngestOutcomeSchema,
  documentIngestResultSchema,
  egressFetchRequestSchema,
  egressFetchResultSchema,
  healthResponseSchema,
  hostCapabilityCallSchema,
  hostCapabilityFailureSchema,
  hostCapabilityRequestSchema,
  hostCapabilityResponseSchema,
  hostCapabilitySuccessSchema,
  installationContextSchema,
  invocationCountsSchema,
  invocationInputSchema,
  invocationOutcomeSchema,
  invocationOutcomes,
  invocationOutputSchema,
  invocationRequestSchema,
  invocationResponseSchema,
  scheduledInvocationInputSchema,
  storageDeleteResultSchema,
  storageGetResultSchema,
  storagePutResultSchema,
  webhookInvocationInputSchema,
  type AppError,
  type AppErrorCode,
  type CapabilitySession,
  type DocumentIngestInput,
  type DocumentIngestResult,
  type EgressFetchRequest,
  type EgressFetchResult,
  type HealthResponse,
  type HostCapabilityCall,
  type HostCapabilityRequest,
  type HostCapabilityResponse,
  type InstallationContext,
  type InvocationInput,
  type InvocationInputKind,
  type InvocationOutcome,
  type InvocationOutput,
  type InvocationRequest,
  type InvocationResponse,
} from "./runtime.js";

export {
  APP_JOB_ENVELOPE_VERSION,
  appJobWakeUpEnvelopeSchema,
  type AppJobWakeUpEnvelope,
} from "./jobs.js";

export {
  resolveInstallation,
  type EffectiveConfiguration,
  type InstallationReadiness,
  type InstallationResolutionResult,
} from "./requirements.js";

export {
  isAdmittedManifest,
  releaseAValidationPolicy,
  validateManifest,
  type AdmittedManifest,
  type ManifestValidationIssue,
  type ManifestValidationPolicy,
  type ManifestValidationResult,
} from "./validate.js";
