import { describe, expect, it } from "vitest";

import { composeAskAgentDescription } from "../../../src/modules/routines/exposure/askAgentDescription.js";

const tool = (toolName: string, description: string) => ({
  toolName,
  description,
  inputSchema: { type: "object" as const, properties: {}, required: [], additionalProperties: false as const },
  routineLineageId: `lineage-${toolName}`,
});

describe("composeAskAgentDescription", () => {
  it("names the business, what it covers, and the tools to prefer", () => {
    const description = composeAskAgentDescription({
      agent: { name: "Acme Support", description: "orders, returns, billing" },
      tools: [tool("check_order", "Look up an order's status."), tool("start_return", "Begin a return.")],
    });

    // US6 AS-1: assembled from configuration, never generated by a model at request time.
    expect(description).toContain("Acme Support");
    expect(description).toContain("orders, returns, billing");
    expect(description).toContain("check_order");
    expect(description).toContain("start_return");
    expect(description).toMatchInlineSnapshot(`"Hold a conversation with Acme Support. It covers orders, returns, billing. Runs the agent's full behavior — persona, directives, and multi-step routines — and continues the same conversation across calls (stateful). Prefer the typed tools for the tasks they name (check_order, start_return); use this for anything else, or when you do not know which tool applies."`);
  });

  it("still describes an agent with no exposed tools and no operator description", () => {
    const description = composeAskAgentDescription({ agent: { name: "Acme Support", description: null }, tools: [] });

    expect(description).toContain("Acme Support");
    // Nothing is invented on the agent's behalf, and no empty tool list is advertised.
    expect(description).not.toContain("Prefer");
    expect(description.trim()).toBe(description);
  });

  it("is stable for the same configuration, because a tool description is cached by clients", () => {
    const input = { agent: { name: "Acme", description: "returns" }, tools: [tool("start_return", "Begin a return.")] };

    expect(composeAskAgentDescription(input)).toBe(composeAskAgentDescription(input));
  });

  it("does not double the period when the operator's description is already a sentence", () => {
    const sentence = composeAskAgentDescription({
      agent: { name: "Acme", description: "We handle orders and returns." },
      tools: [],
    });

    expect(sentence).toContain("It covers We handle orders and returns.");
    expect(sentence).not.toContain("..");
  });

  it("says the list is partial rather than reading as the whole catalog", () => {
    const many = Array.from({ length: 20 }, (_, index) => tool(`tool_${index}`, "A tool."));
    const description = composeAskAgentDescription({ agent: { name: "Acme", description: null }, tools: many });

    // Without this a model reads the named twelve as exhaustive and sends every other task to
    // `ask_agent` instead of the tool that fits it.
    expect(description).toContain("and others");
  });

  it("bounds a long list rather than letting the catalog set the description's size", () => {
    const many = Array.from({ length: 40 }, (_, index) => tool(`tool_${index}`, "A tool."));
    const description = composeAskAgentDescription({ agent: { name: "Acme", description: null }, tools: many });

    expect(description.length).toBeLessThan(2_000);
    expect(description).toContain("tool_0");
  });
});
