import type { ChatService } from "../../modules/chat/services/chatService.js";
import type { ChatBootstrapService } from "../../modules/chat/services/chatBootstrapService.js";
import type { ChatHistoryService } from "../../modules/chat/services/chatHistoryService.js";
import type { AssistantChatService } from "../../modules/chat/services/assistantChatService.js";
import type { AssistantHistoryService } from "../../modules/chat/services/assistantHistoryService.js";
import type { DocumentDeletionService } from "../../modules/documents/services/documentDeletionService.js";
import type { DocumentIngestionService } from "../../modules/documents/services/documentIngestionService.js";
import type { DocumentImportService } from "../../modules/documents/services/documentImportService.js";
import type { DocumentSearchHistoryService } from "../../modules/documents/services/documentSearchHistoryService.js";
import type { DocumentSearchService } from "../../modules/documents/services/documentSearchService.js";
import type { DocumentProcessingWorker } from "../../modules/documents/services/documentProcessingWorker.js";
import type { DocumentJobConsumerPort } from "../../modules/documents/services/documentJobConsumer.js";
import type { WorkspaceIngestionReprocessService } from "../../modules/documents/services/workspaceIngestionReprocessService.js";
import type { IngestionSettingsService } from "../../modules/settings/services/ingestionSettingsService.js";
import type { PlatformSettingsService } from "../../modules/settings/services/platformSettingsService.js";
import type { RetrievalSettingsService } from "../../modules/settings/services/retrievalSettingsService.js";
import type { RetrievalAnswerService } from "../../modules/retrieval/services/retrievalAnswerService.js";
import type { RetrievalSearchService } from "../../modules/retrieval/services/retrievalSearchService.js";
import type { AuthService } from "../../modules/auth/services/authService.js";
import type { AccountAccessService } from "../../modules/account/services/accountAccessService.js";
import type { AccountInvitationService } from "../../modules/account/services/accountInvitationService.js";
import type { AuditService } from "../../modules/audit/services/auditService.js";
import type { WorkspaceService } from "../../modules/workspace/services/workspaceService.js";
import type { WorkspaceSummaryService } from "../../modules/workspace/services/workspaceSummaryService.js";
import type { WorkspaceSessionService } from "../../modules/auth/services/workspaceSessionService.js";
import type { WorkspaceRepositoryPort } from "../../db/repositories/workspaceRepository.js";
import type { AccountRepositoryPort } from "../../modules/auth/services/authService.js";
import type { BootstrapGreetingCacheRepositoryPort } from "../../db/repositories/bootstrapGreetingCacheRepository.js";
import type { ConversationRepositoryPort } from "../../db/repositories/conversationRepository.js";
import type { MessageRepositoryPort } from "../../db/repositories/messageRepository.js";
import type { ConnectorRegistry } from "../../modules/connectors/services/connectorRegistry.js";
import type { Database } from "../../shared/infra/database.js";
import type { Env } from "../config/env.js";
import type { AppLogger } from "../../shared/observability/logger.js";
import type { AbuseControlService } from "../../modules/security/services/abuseControlService.js";
import type { ProductAnalyticsPort } from "../../shared/analytics/productAnalyticsService.js";
import type { TelemetryService } from "../../shared/observability/telemetry/telemetryService.js";
import type { IncidentReportingService } from "../../shared/incidents/incidentReportingService.js";
import type { MetricsRegistry } from "../../shared/observability/metrics/metricsRegistry.js";
import type { CapabilityPolicy } from "../../shared/domain/capabilityPolicy.js";
import type { UsageLimitPolicy } from "../../shared/domain/usageLimitPolicy.js";
import type { ApplicationModuleCoordinator, ApplicationRouteMount } from "../composition/applicationModule.js";
import type { ChatActionProviderPort } from "../../modules/chat/services/chatActionProvider.js";
import type { ContactHistoryProviderPort } from "../../modules/chat/services/contactHistoryProvider.js";
import type { UserRepositoryPort } from "../../db/repositories/userRepository.js";

export interface AppDependencies {
  env: Env;
  logger: AppLogger;
  metricsRegistry: MetricsRegistry | null;
  telemetryService: TelemetryService;
  incidentReportingService: IncidentReportingService;
  productAnalyticsService: ProductAnalyticsPort;
  capabilityPolicy: CapabilityPolicy;
  usageLimitPolicy: UsageLimitPolicy;
  chatActionProvider: ChatActionProviderPort;
  contactHistoryProvider: ContactHistoryProviderPort;
  applicationRouteMounts: ApplicationRouteMount[];
  applicationModules: ApplicationModuleCoordinator;
  authService: AuthService;
  accountAccessService: AccountAccessService;
  accountInvitationService: AccountInvitationService;
  workspaceSessionService: WorkspaceSessionService;
  abuseControlService: AbuseControlService;
  auditService: AuditService;
  workspaceService: WorkspaceService;
  workspaceSummaryService: WorkspaceSummaryService;
  ingestionSettingsService: IngestionSettingsService;
  retrievalSettingsService: RetrievalSettingsService;
  documentIngestionService: DocumentIngestionService;
  documentImportService: DocumentImportService;
  documentSearchService: DocumentSearchService;
  documentSearchHistoryService: DocumentSearchHistoryService;
  workspaceIngestionReprocessService: WorkspaceIngestionReprocessService;
  documentProcessingWorker: DocumentProcessingWorker;
  documentJobConsumer?: DocumentJobConsumerPort;
  documentDeletionService: DocumentDeletionService;
  chatService: ChatService;
  chatBootstrapService: ChatBootstrapService;
  chatHistoryService: ChatHistoryService;
  assistantChatService: AssistantChatService;
  assistantHistoryService: AssistantHistoryService;
  retrievalSearchService: RetrievalSearchService;
  retrievalAnswerService: RetrievalAnswerService;
  platformSettingsService: PlatformSettingsService;
  workspaceRepository: WorkspaceRepositoryPort;
  userRepository: UserRepositoryPort;
  accountRepository: AccountRepositoryPort;
  bootstrapGreetingCacheRepository: BootstrapGreetingCacheRepositoryPort;
  conversationRepository: ConversationRepositoryPort;
  messageRepository: MessageRepositoryPort;
  connectorRegistry: ConnectorRegistry;
  connectorDb: Database;
}
