import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";

import { getEnvContract, listRequiredKeys } from "./support/env-contract.mjs";

export const parseEnvFile = (source) => {
  const values = {};
  for (const rawLine of source.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) {
      continue;
    }
    const separator = line.indexOf("=");
    if (separator === -1) {
      continue;
    }
    const key = line.slice(0, separator).trim();
    const value = line.slice(separator + 1);
    values[key] = value;
  }
  return values;
};

export const readEnvFile = async (filePath) => {
  try {
    const source = await fs.readFile(filePath, "utf8");
    return parseEnvFile(source);
  } catch (error) {
    if (error.code === "ENOENT") {
      return null;
    }
    throw error;
  }
};

export const classifyEnvState = (values, contract = getEnvContract()) => {
  if (!values) {
    return "missing";
  }

  const requiredKeys = listRequiredKeys(values, contract);
  const missingRequired = requiredKeys.filter((key) => {
    const value = values[key];
    return value === undefined || value === "";
  });

  if (missingRequired.length > 0) {
    return "partial";
  }

  return "valid";
};

export const buildEnvValues = (existingValues, updates, contract = getEnvContract()) => {
  const merged = { ...contract.defaults, ...(existingValues ?? {}), ...updates };

  if (!merged.LLM_PROVIDER) {
    merged.LLM_PROVIDER = contract.defaults.LLM_PROVIDER || "openai";
  }

  return merged;
};

export const renderEnvFile = (values, contract = getEnvContract()) => {
  const lines = ["# Generated by Radioso bootstrap. Edit with care."];
  for (const key of contract.keyOrder) {
    if (!(key in values)) {
      continue;
    }
    const value = values[key];
    if (value === undefined || value === null || value === "") {
      continue;
    }
    lines.push(`${key}=${value}`);
  }
  return `${lines.join("\n")}\n`;
};

export const enforceEnvFilePermissions = async (filePath) => {
  try {
    await fs.chmod(filePath, 0o600);
  } catch (error) {
    if (error.code === "ENOENT") {
      return;
    }
    throw error;
  }
};

export const writeEnvFileAtomic = async (filePath, source) => {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  const tempPath = path.join(
    path.dirname(filePath),
    `.${path.basename(filePath)}.${crypto.randomUUID()}.tmp`,
  );
  let handle;

  try {
    handle = await fs.open(tempPath, "wx", 0o600);
    await handle.writeFile(source, "utf8");
    await handle.close();
    handle = undefined;
    await fs.rename(tempPath, filePath);
  } catch (error) {
    await handle?.close();
    await fs.rm(tempPath, { force: true });
    throw error;
  }
};
