name: Deploy Live (EU)

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-cloud-run.yml
    permissions:
      contents: read
      id-token: write
    with:
      github_environment: live-eu
      artifact_repository: radioso-live-eu
      backend_service: radioso-live-eu-backend
      crawler_worker_service: radioso-live-eu-crawler-worker
      frontend_service: radioso-live-eu-frontend
      worker_service: radioso-live-eu-worker
      require_main_branch: true
      radioso_edition: enterprise
